// generated by newgenasym  Mon Mar 02 00:55:23 2015


module caen_buffer (cntrl, in_anal, out_att, out_clip, vref5m);
    input cntrl;
    input in_anal;
    output out_att;
    output out_clip;
    input vref5m;


    initial
        begin
        end

endmodule
