-- generated by newgenasym Mon Mar 02 00:55:23 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_buffer is
    port (    
	CNTRL:     IN     STD_LOGIC;    
	IN_ANAL:   IN     STD_LOGIC;    
	OUT_ATT:   OUT    STD_LOGIC;    
	OUT_CLIP:  OUT    STD_LOGIC;    
	VREF5M:    IN     STD_LOGIC);
end caen_buffer;
