-- generated by newgenasym Tue May 12 17:59:41 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CAEN_BUFFER is
    port (    
	CNTRL:     IN     std_logic;    
	IN_ANAL:   IN     std_logic;    
	OUT_ATT:   OUT    std_logic;    
	OUT_CLIP:  OUT    std_logic;    
	VREF5M:    IN     std_logic);
end CAEN_BUFFER;
