// Generated by Part Developer

// Modified to support swift models
`timescale 1ns/100ps

module \10h131  (d,en,q,r,s,clk,\q* );
	parameter   size = 1;
	input [size-1:0] d;
	input en;
	output [size-1:0] q;
	input r;
	input s;
	input clk;
	output [size-1:0] \q* ;




	MC10h131 inst1 [size-1:0] 
		(
		,
		clk,
		s,
		d,
		en,
		r,
		,
		,
		,
		,
		,
		q,
		\q* 
		);



endmodule

