// generated by newgenasym  Thu Mar 05 16:20:47 2015


module caen_coms (caen_out_anal, clk, data, data_rdy, gt2_n, gt2_p, gt_n,
        gt_nim, gt_p, gt_ttl, le, pulse_in_anal, scope_out_anal,
        sync24_lvds_n, sync24_lvds_p, sync24_n, sync24_p,
        sync_lvds_n, sync_lvds_p, sync_n, sync_p);
    output [0:7] caen_out_anal;
    input clk;
    input data;
    input data_rdy;
    output gt2_n;
    output gt2_p;
    input gt_n;
    output gt_nim;
    input gt_p;
    output gt_ttl;
    input le;
    input [0:11] pulse_in_anal;
    output [0:7] scope_out_anal;
    output sync24_lvds_n;
    output sync24_lvds_p;
    input sync24_n;
    input sync24_p;
    output sync_lvds_n;
    output sync_lvds_p;
    input sync_n;
    input sync_p;


    initial
        begin
        end

endmodule
