// generated by newgenasym  Sat Feb 28 23:31:48 2015


module mc10h131 (cc, \ce1* , \ce2* , d1, d2, gnd1, gnd2, q1, \q1* , q2, \q2* , r1, r2, s1,
        s2, vee);
    input cc;
    input \ce1* ;
    input \ce2* ;
    input d1;
    input d2;
    input gnd1;
    input gnd2;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    input r1;
    input r2;
    input s1;
    input s2;
    input vee;


    initial
        begin
        end

endmodule
