-- generated by newgenasym Sat Feb 28 23:31:48 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc10h131 is
    port (    
	CC:        IN     STD_LOGIC;    
	\ce1*\:    IN     STD_LOGIC;    
	\ce2*\:    IN     STD_LOGIC;    
	D1:        IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	\q1*\:     OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	\q2*\:     OUT    STD_LOGIC;    
	R1:        IN     STD_LOGIC;    
	R2:        IN     STD_LOGIC;    
	S1:        IN     STD_LOGIC;    
	S2:        IN     STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end mc10h131;
