// generated by newgenasym  Mon Sep 13 13:56:40 2010


module \8061  (in, in_coil, out_coil, out_nc, out_no);
    inout in;
    inout in_coil;
    inout out_coil;
    inout out_nc;
    inout out_no;


    initial
        begin
        end

endmodule
