-- generated by newgenasym Mon Sep 13 13:56:40 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \8061\ is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	IN_COIL:   INOUT  STD_LOGIC;    
	OUT_COIL:  INOUT  STD_LOGIC;    
	OUT_NC:    INOUT  STD_LOGIC;    
	OUT_NO:    INOUT  STD_LOGIC);
end \8061\;
