// generated by newgenasym  Mon Oct  4 14:13:30 2010


module euroconn (a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20,
        a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a4,
        a5, a6, a7, a8, a9, b1, b10, b11, b12, b13, b14, b15, b16, b17, b18,
        b19, b2, b20, b21, b22, b23, b24, b25, b26, b27, b28, b29, b3, b30,
        b31, b32, b4, b5, b6, b7, b8, b9, c1, c10, c11, c12, c13, c14, c15,
        c16, c17, c18, c19, c2, c20, c21, c22, c23, c24, c25, c26, c27,
        c28, c29, c3, c30, c31, c32, c4, c5, c6, c7, c8, c9);
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a16;
    inout a17;
    inout a18;
    inout a19;
    inout a2;
    inout a20;
    inout a21;
    inout a22;
    inout a23;
    inout a24;
    inout a25;
    inout a26;
    inout a27;
    inout a28;
    inout a29;
    inout a3;
    inout a30;
    inout a31;
    inout a32;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout b1;
    inout b10;
    inout b11;
    inout b12;
    inout b13;
    inout b14;
    inout b15;
    inout b16;
    inout b17;
    inout b18;
    inout b19;
    inout b2;
    inout b20;
    inout b21;
    inout b22;
    inout b23;
    inout b24;
    inout b25;
    inout b26;
    inout b27;
    inout b28;
    inout b29;
    inout b3;
    inout b30;
    inout b31;
    inout b32;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout b9;
    inout c1;
    inout c10;
    inout c11;
    inout c12;
    inout c13;
    inout c14;
    inout c15;
    inout c16;
    inout c17;
    inout c18;
    inout c19;
    inout c2;
    inout c20;
    inout c21;
    inout c22;
    inout c23;
    inout c24;
    inout c25;
    inout c26;
    inout c27;
    inout c28;
    inout c29;
    inout c3;
    inout c30;
    inout c31;
    inout c32;
    inout c4;
    inout c5;
    inout c6;
    inout c7;
    inout c8;
    inout c9;


    initial
        begin
        end

endmodule
