-- generated by newgenasym Tue Apr  5 18:47:15 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mur105 is
    port (    
	AN:        INOUT  STD_LOGIC;    
	CAT:       INOUT  STD_LOGIC);
end mur105;
