// generated by newgenasym  Mon Aug 17 17:07:36 2009


module tlc274 (nin, nvss, out, pin, pvss);
    input nin;
    inout nvss;
    output out;
    input pin;
    inout pvss;


    initial
        begin
        end

endmodule
