-- generated by newgenasym Mon Aug 17 17:07:36 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tlc274 is
    port (    
	NIN:       IN     STD_LOGIC;    
	NVSS:      INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	PIN:       IN     STD_LOGIC;    
	PVSS:      INOUT  STD_LOGIC);
end tlc274;
