// generated by newgenasym  Wed Jul 16 16:49:56 2014


module \74fhct597  (d, ds, \mr* , \pl* , q, shcp, stcp);
    input [7:0] d;
    input ds;
    input \mr* ;
    input \pl* ;
    output q;
    input shcp;
    input stcp;


    initial
        begin
        end

endmodule
