-- generated by newgenasym Wed Jul 16 16:49:56 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74fhct597\ is
    port (    
	D:         IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	DS:        IN     STD_LOGIC;    
	\mr*\:     IN     STD_LOGIC;    
	\pl*\:     IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	SHCP:      IN     STD_LOGIC;    
	STCP:      IN     STD_LOGIC);
end \74fhct597\;
