-- generated by newgenasym Sun Mar 01 22:00:55 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc10e016 is
    port (    
	\ce*\:     IN     STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	GND0:      IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	MR:        IN     STD_LOGIC;    
	P0:        IN     STD_LOGIC;    
	P1:        IN     STD_LOGIC;    
	P2:        IN     STD_LOGIC;    
	P3:        IN     STD_LOGIC;    
	P4:        IN     STD_LOGIC;    
	P5:        IN     STD_LOGIC;    
	P6:        IN     STD_LOGIC;    
	P7:        IN     STD_LOGIC;    
	\pe*\:     IN     STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	Q5:        OUT    STD_LOGIC;    
	Q6:        OUT    STD_LOGIC;    
	Q7:        OUT    STD_LOGIC;    
	\tc*\:     OUT    STD_LOGIC;    
	TCLD:      IN     STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end mc10e016;
