// generated by newgenasym  Sat Feb 28 19:58:30 2015


module ribbon_delay (pulse_in_n, pulse_in_p, pulse_out_n, pulse_out_p);
    input pulse_in_n;
    input pulse_in_p;
    output pulse_out_n;
    output pulse_out_p;


    initial
        begin
        end

endmodule
