-- generated by newgenasym Sat Feb 28 19:58:30 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ribbon_delay is
    port (    
	PULSE_IN_N: IN     STD_LOGIC;    
	PULSE_IN_P: IN     STD_LOGIC;    
	PULSE_OUT_N: OUT    STD_LOGIC;    
	PULSE_OUT_P: OUT    STD_LOGIC);
end ribbon_delay;
