-- generated by newgenasym Tue Apr 21 13:20:23 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74s32 is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	B1:        IN     STD_LOGIC;    
	B2:        IN     STD_LOGIC;    
	B3:        IN     STD_LOGIC;    
	B4:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y1:        OUT    STD_LOGIC;    
	Y2:        OUT    STD_LOGIC;    
	Y3:        OUT    STD_LOGIC;    
	Y4:        OUT    STD_LOGIC);
end sn74s32;
