-- generated by newgenasym Tue Nov 04 11:09:50 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity coto2342 is
    port (    
	CTRL_IN:   INOUT  STD_LOGIC;    
	CTRL_OUT:  INOUT  STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NO1:       INOUT  STD_LOGIC;    
	NO2:       INOUT  STD_LOGIC);
end coto2342;
