// generated by newgenasym  Sun Mar 01 15:00:23 2015


module sy100el34l (clk, \clk* , \en* , gnd0, gnd1, gnd2, mr, q0, \q0* , q1, \q1* , q2, \q2* ,
        vbb, vee);
    input clk;
    input \clk* ;
    input \en* ;
    input gnd0;
    input gnd1;
    input gnd2;
    input mr;
    output q0;
    output \q0* ;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    output vbb;
    input vee;


    initial
        begin
        end

endmodule
