-- generated by newgenasym Sun Mar 01 15:00:23 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sy100el34l is
    port (    
	CLK:       IN     STD_LOGIC;    
	\clk*\:    IN     STD_LOGIC;    
	\en*\:     IN     STD_LOGIC;    
	GND0:      IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	MR:        IN     STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	\q0*\:     OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	\q1*\:     OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	\q2*\:     OUT    STD_LOGIC;    
	VBB:       OUT    STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end sy100el34l;
