// generated by newgenasym  Wed Oct  6 10:34:08 2010


module \10h125  (a, \b* , v, y);
    parameter    section = 3;
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] \b* ;
    output v;
    output [size-1:0] y;


    initial
        begin
        end

endmodule
