-- generated by newgenasym Wed Oct  6 10:34:08 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h125\ is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\b*\:      IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	V:         OUT    STD_LOGIC;    
	Y:         OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \10h125\;
