-- generated by newgenasym Thu May 28 15:10:16 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity eleccap is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end eleccap;
