// generated by genview  Fri Jan 16 22:43:51 1998

`timescale 1ns/100ps

module \10e116  (a, \b* , ref, y, \y* );
    parameter    size = 1;
    parameter    VBBD0 = "VBBD0";
    parameter    VBBD0_ = "VBBD0_";
    input [size-1:0] a;
    input [size-1:0] \b* ;
    output [size-1:0] y;
    output ref;
    output [size-1:0] \y* ;


    MC10E116P #(VBBD0, VBBD0_)  inst1[size-1:0] (/*.VBB*/ ref,
			                   /*.D0*/ a,
                               /*.D0_*/ \b* ,
                               /*.Q0*/ y,
                               /*.Q0_*/ \y*  );
endmodule
