-- generated by newgenasym Mon Aug  2 15:49:02 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \g3vm-352j\ is
    port (    
	CTRL_IN:   INOUT  STD_LOGIC;    
	CTRL_OUT:  INOUT  STD_LOGIC;    
	SIG_IN:    IN     STD_LOGIC;    
	SIG_OUT:   OUT    STD_LOGIC);
end \g3vm-352j\;
