-- generated by newgenasym Wed Nov  3 13:42:36 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsmd0603 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end rsmd0603;
