-- generated by newgenasym Mon Apr 20 11:43:26 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \3006p_trimpot\ is
    port (    
	CCW:       INOUT  STD_LOGIC;    
	CW:        INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end \3006p_trimpot\;
