// generated by newgenasym  Thu Apr 16 14:38:18 2015


module trigger_logic (dgt_gate, gt, \lo* , over_thresh1_n, over_thresh1_p,
        over_thresh2_n, over_thresh2_p, posneg1_n, posneg1_p,
        posneg2_n, posneg2_p, trig1_out_n, trig1_out_p,
        trig1_out_ttl, trig2_out_n, trig2_out_p, trig2_out_ttl);
    input dgt_gate;
    input gt;
    input \lo* ;
    input over_thresh1_n;
    input over_thresh1_p;
    input over_thresh2_n;
    input over_thresh2_p;
    input posneg1_n;
    input posneg1_p;
    input posneg2_n;
    input posneg2_p;
    output trig1_out_n;
    output trig1_out_p;
    output trig1_out_ttl;
    output trig2_out_n;
    output trig2_out_p;
    output trig2_out_ttl;


    initial
        begin
        end

endmodule
