// generated by newgenasym  Sat Mar 07 19:13:05 2015


module select_lo_src (\ddgt* , lo_sel, lo_star2, lo_star_out_n, lo_star_out_p,
        \mtcd_lo* );
    input \ddgt* ;
    input lo_sel;
    output lo_star2;
    output lo_star_out_n;
    output lo_star_out_p;
    input \mtcd_lo* ;


    initial
        begin
        end

endmodule
