// generated by newgenasym  Sat Feb 28 18:14:04 2015


module select_lo_src (\ddgt* , lo, \lo* , lo_sel, \mtcd_lo* );
    input \ddgt* ;
    output lo;
    output \lo* ;
    input lo_sel;
    input \mtcd_lo* ;


    initial
        begin
        end

endmodule
