// generated by newgenasym  Thu Mar 05 15:15:57 2015


module select_lo_src (\ddgt* , lo, \lo* , lo_sel, lo_star2, \mtcd_lo* );
    input \ddgt* ;
    output lo;
    output \lo* ;
    input lo_sel;
    output lo_star2;
    input \mtcd_lo* ;


    initial
        begin
        end

endmodule
