-- generated by newgenasym Thu Mar 05 15:15:57 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity select_lo_src is
    port (    
	\ddgt*\:   IN     STD_LOGIC;    
	LO:        OUT    STD_LOGIC;    
	\lo*\:     OUT    STD_LOGIC;    
	LO_SEL:    IN     STD_LOGIC;    
	LO_STAR2:  OUT    STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC);
end select_lo_src;
