-- generated by newgenasym Sat Mar 07 19:13:05 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity select_lo_src is
    port (    
	\ddgt*\:   IN     STD_LOGIC;    
	LO_SEL:    IN     STD_LOGIC;    
	LO_STAR2:  OUT    STD_LOGIC;    
	LO_STAR_OUT_N: OUT    STD_LOGIC;    
	LO_STAR_OUT_P: OUT    STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC);
end select_lo_src;
