// generated by newgenasym  Wed May 13 15:08:28 2015


module ths3061 (\vin+ , \vin- , vout, \vs+ , \vs- );
    inout \vin+ ;
    inout \vin- ;
    inout vout;
    input \vs+ ;
    input \vs- ;


    initial
        begin
        end

endmodule
