-- generated by newgenasym Wed May 13 15:08:28 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ths3061 is
    port (    
	\vin+\:    INOUT  STD_LOGIC;    
	\vin-\:    INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC;    
	\vs+\:     IN     STD_LOGIC;    
	\vs-\:     IN     STD_LOGIC);
end ths3061;
