// generated by newgenasym  Mon Oct 20 17:01:19 2014


module pot (a, b, c);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;
    inout c;


    initial
        begin
        end

endmodule
