// generated by newgenasym  Sun Mar 01 00:00:53 2015


module mc10e101 (d0a, d0b, d0c, d0d, d1a, d1b, d1c, d1d, d2a, d2b, d2c, d2d, d3a,
        d3b, d3c, d3d, gnd0, gnd1, gnd2, q0, \q0* , q1, \q1* , q2, \q2* , q3,
        \q3* , vee);
    input d0a;
    input d0b;
    input d0c;
    input d0d;
    input d1a;
    input d1b;
    input d1c;
    input d1d;
    input d2a;
    input d2b;
    input d2c;
    input d2d;
    input d3a;
    input d3b;
    input d3c;
    input d3d;
    input gnd0;
    input gnd1;
    input gnd2;
    output q0;
    output \q0* ;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    output q3;
    output \q3* ;
    input vee;


    initial
        begin
        end

endmodule
