-- generated by newgenasym Sun Mar 01 00:00:53 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc10e101 is
    port (    
	D0A:       IN     STD_LOGIC;    
	D0B:       IN     STD_LOGIC;    
	D0C:       IN     STD_LOGIC;    
	D0D:       IN     STD_LOGIC;    
	D1A:       IN     STD_LOGIC;    
	D1B:       IN     STD_LOGIC;    
	D1C:       IN     STD_LOGIC;    
	D1D:       IN     STD_LOGIC;    
	D2A:       IN     STD_LOGIC;    
	D2B:       IN     STD_LOGIC;    
	D2C:       IN     STD_LOGIC;    
	D2D:       IN     STD_LOGIC;    
	D3A:       IN     STD_LOGIC;    
	D3B:       IN     STD_LOGIC;    
	D3C:       IN     STD_LOGIC;    
	D3D:       IN     STD_LOGIC;    
	GND0:      IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	\q0*\:     OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	\q1*\:     OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	\q2*\:     OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	\q3*\:     OUT    STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end mc10e101;
