// generated by newgenasym  Mon Mar 02 16:07:00 2015


module caen_dig_coms (gt_n, gt_nim, gt_p, sync24_lvds_n, sync24_lvds_p,
        sync24_n, sync24_p, sync_lvds_n, sync_lvds_p, sync_n,
        sync_p);
    input gt_n;
    input gt_nim;
    input gt_p;
    input sync24_lvds_n;
    input sync24_lvds_p;
    input sync24_n;
    input sync24_p;
    input sync_lvds_n;
    input sync_lvds_p;
    input sync_n;
    input sync_p;


    initial
        begin
        end

endmodule
