// generated by newgenasym  Thu Mar 05 16:04:45 2015


module caen_dig_coms (gt2_n, gt2_p, gt_n, gt_nim, gt_p, gt_ttl, sync24_lvds_n,
        sync24_lvds_p, sync24_n, sync24_p, sync_lvds_n,
        sync_lvds_p, sync_n, sync_p);
    output gt2_n;
    output gt2_p;
    input gt_n;
    output gt_nim;
    input gt_p;
    output gt_ttl;
    output sync24_lvds_n;
    output sync24_lvds_p;
    input sync24_n;
    input sync24_p;
    output sync_lvds_n;
    output sync_lvds_p;
    input sync_n;
    input sync_p;


    initial
        begin
        end

endmodule
