-- generated by newgenasym Thu Mar 05 19:39:10 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_dig_coms is
    port (    
	GT2_N:     OUT    STD_LOGIC;    
	GT2_P:     OUT    STD_LOGIC;    
	GT_N:      IN     STD_LOGIC;    
	GT_NIM:    OUT    STD_LOGIC;    
	GT_P:      IN     STD_LOGIC;    
	GT_TTL:    OUT    STD_LOGIC;    
	SYNC24_LVDS_N: OUT    STD_LOGIC;    
	SYNC24_LVDS_P: OUT    STD_LOGIC;    
	SYNC24_N:  IN     STD_LOGIC;    
	SYNC24_P:  IN     STD_LOGIC;    
	SYNC24_TTL: OUT    STD_LOGIC;    
	SYNC_LVDS_N: OUT    STD_LOGIC;    
	SYNC_LVDS_P: OUT    STD_LOGIC;    
	SYNC_N:    IN     STD_LOGIC;    
	SYNC_P:    IN     STD_LOGIC;    
	SYNC_TTL:  OUT    STD_LOGIC);
end caen_dig_coms;
