-- generated by newgenasym Mon Mar 02 16:07:00 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_dig_coms is
    port (    
	GT_N:      IN     STD_LOGIC;    
	GT_NIM:    IN     STD_LOGIC;    
	GT_P:      IN     STD_LOGIC;    
	SYNC24_LVDS_N: IN     STD_LOGIC;    
	SYNC24_LVDS_P: IN     STD_LOGIC;    
	SYNC24_N:  IN     STD_LOGIC;    
	SYNC24_P:  IN     STD_LOGIC;    
	SYNC_LVDS_N: IN     STD_LOGIC;    
	SYNC_LVDS_P: IN     STD_LOGIC;    
	SYNC_N:    IN     STD_LOGIC;    
	SYNC_P:    IN     STD_LOGIC);
end caen_dig_coms;
