// generated by newgenasym  Tue May 18 12:01:39 2010


module \7906_l  (ground, \input , \output );
    inout ground;
    input \input ;
    output \output ;


    initial
        begin
        end

endmodule
