-- generated by newgenasym Wed Mar 04 11:59:35 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ttl_ecl is
    port (    
	ECL_IN_N:  IN     STD_LOGIC;    
	ECL_IN_P:  IN     STD_LOGIC;    
	ECL_OUT_N: OUT    STD_LOGIC;    
	ECL_OUT_P: OUT    STD_LOGIC;    
	TTL_IN:    IN     STD_LOGIC;    
	TTL_OUT:   OUT    STD_LOGIC);
end ttl_ecl;
