// generated by newgenasym  Wed Jan 28 19:30:00 2015


module ss22sdp2 (p1, p2, t_a1, t_a2, t_b1, t_b2);
    inout p1;
    inout p2;
    inout t_a1;
    inout t_a2;
    inout t_b1;
    inout t_b2;


    initial
        begin
        end

endmodule
