-- generated by newgenasym Wed Jan 28 19:30:00 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ss22sdp2 is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	T_A1:      INOUT  STD_LOGIC;    
	T_A2:      INOUT  STD_LOGIC;    
	T_B1:      INOUT  STD_LOGIC;    
	T_B2:      INOUT  STD_LOGIC);
end ss22sdp2;
