// generated by newgenasym  Wed May 20 14:29:03 2015


module pickering113fc (\cntrl+ , \cntrl- , in1, in2, out);
    inout \cntrl+ ;
    inout \cntrl- ;
    inout in1;
    inout in2;
    inout out;


    initial
        begin
        end

endmodule
