-- generated by newgenasym Wed May 20 14:29:03 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pickering113fc is
    port (    
	\cntrl+\:  INOUT  STD_LOGIC;    
	\cntrl-\:  INOUT  STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end pickering113fc;
