-- generated by newgenasym Thu Jan 08 15:59:36 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h124\ is
    port (    
	COMMON:    IN     STD_LOGIC;    
	D:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC);
end \10h124\;
