// generated by newgenasym  Mon Jan 26 19:02:07 2015


module ids_c34 (pin1, pin10, pin11, pin12, pin13, pin14, pin15, pin16, pin17,
        pin18, pin19, pin2, pin20, pin21, pin22, pin23, pin24, pin25,
        pin26, pin27, pin28, pin29, pin3, pin30, pin31, pin32, pin33,
        pin34, pin4, pin5, pin6, pin7, pin8, pin9);
    inout pin1;
    inout pin10;
    inout pin11;
    inout pin12;
    inout pin13;
    inout pin14;
    inout pin15;
    inout pin16;
    inout pin17;
    inout pin18;
    inout pin19;
    inout pin2;
    inout pin20;
    inout pin21;
    inout pin22;
    inout pin23;
    inout pin24;
    inout pin25;
    inout pin26;
    inout pin27;
    inout pin28;
    inout pin29;
    inout pin3;
    inout pin30;
    inout pin31;
    inout pin32;
    inout pin33;
    inout pin34;
    inout pin4;
    inout pin5;
    inout pin6;
    inout pin7;
    inout pin8;
    inout pin9;


    initial
        begin
        end

endmodule
