-- generated by newgenasym Tue May 18 12:01:04 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \pin names\ is
    port (    
	NAME:      IN     STD_LOGIC);
end \pin names\;
