// generated by newgenasym  Wed Jul 13 10:11:40 2011


module adcmp566 (in, \in* , le, \le* , nc, nc2, q, \q* );
    input in;
    input \in* ;
    input le;
    input \le* ;
    inout nc;
    inout nc2;
    output q;
    output \q* ;


    initial
        begin
        end

endmodule
