-- generated by newgenasym Wed Jul 13 10:11:40 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adcmp566 is
    port (    
	\in\:      IN     STD_LOGIC;    
	\in*\:     IN     STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	\le*\:     IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC);
end adcmp566;
