-- generated by newgenasym Sun Mar 01 03:06:01 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tubii_spkr is
    port (    
	SPKR_SIG:  IN     STD_LOGIC);
end tubii_spkr;
