-- generated by newgenasym Tue May 18 12:04:48 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity BAS16LT1 is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC);
end BAS16LT1;
