-- generated by newgenasym Tue May 26 14:10:28 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bas16lt1 is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC);
end bas16lt1;
