// generated by newgenasym  Wed Oct 29 13:44:37 2014


module \10ep90  (d, \d* , q, \q* );
    input d;
    input \d* ;
    output q;
    output \q* ;


    initial
        begin
        end

endmodule
