// generated by newgenasym  Wed Oct 01 13:43:16 2014


module \10h131  (clk, d, en, q, \q* , r, s);
    parameter    size = 1;
    input clk;
    input [size-1:0] d;
    input en;
    output [size-1:0] q;
    output [size-1:0] \q* ;
    input r;
    input s;


    initial
        begin
        end

endmodule
