// generated by newgenasym  Mon Nov 15 17:02:44 2010


module inductor_1206 (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
