-- generated by newgenasym Mon Nov 15 17:02:44 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity inductor_1206 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end inductor_1206;
