-- generated by newgenasym Thu May 28 01:16:03 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity back_ports is
    port (    
	UNNUSED_MZ: IN     STD_LOGIC_VECTOR (0 TO 15));
end back_ports;
