// generated by newgenasym  Tue Nov 04 17:44:44 2014


module hct374 (clk, \clr* , d, q);
    input clk;
    input \clr* ;
    input d;
    output q;


    initial
        begin
        end

endmodule
