-- generated by newgenasym Tue Nov 04 17:44:44 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hct374 is
    port (    
	CLK:       IN     STD_LOGIC;    
	\clr*\:    IN     STD_LOGIC;    
	D:         IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC);
end hct374;
