// generated by newgenasym  Mon Oct  4 14:19:14 2010


module \10e016  (\ce* , clk, mr, p, \pe* , q, \tc* , tcld);
    input \ce* ;
    input clk;
    input mr;
    input [7:0] p;
    input \pe* ;
    output [7:0] q;
    output \tc* ;
    input tcld;


    initial
        begin
        end

endmodule
