// generated by newgenasym  Tue May 18 12:06:05 2010


module mc10198 (cext, cs, d, \ecl#20com , \ecl#20ref , \eneg* , \epos* , epwc, hstrig, le,
        \off#20adj , q, \q* , \qr* , reset, \reset* , rext, rs, trig, \trig* );
    input cext;
    inout cs;
    input [7:0] d;
    inout \ecl#20com ;
    inout \ecl#20ref ;
    input \eneg* ;
    input \epos* ;
    input epwc;
    input hstrig;
    input le;
    input \off#20adj ;
    output q;
    output \q* ;
    output \qr* ;
    input reset;
    input \reset* ;
    input rext;
    inout rs;
    input trig;
    input \trig* ;


    initial
        begin
        end

endmodule
