-- generated by newgenasym Thu Aug 26 15:43:23 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap_1210 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end cap_1210;
