// generated by newgenasym  Wed Aug 20 16:01:43 2014


module hct04 (a, \y* );
    parameter    size = 1;
    input [size-1:0] a;
    output [size-1:0] \y* ;


    initial
        begin
        end

endmodule
