-- generated by newgenasym Wed Aug 20 16:01:43 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hct04 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y*\:      OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end hct04;
