// generated by newgenasym  Thu Mar 05 12:44:00 2015


module tubii_pcb (ecl_to_lvds_in, ecl_to_lvds_out_n, ecl_to_lvds_out_p,
        ecl_to_nim_in, ecl_to_nim_out, ecl_to_ttl_in,
        ecl_to_ttl_out, lvds_to_ecl_in_n, lvds_to_ecl_in_p,
        lvds_to_ecl_out, nim_to_ecl_in, nim_to_ecl_out,
        ttl_to_ecl_in, ttl_to_ecl_out);
    input ecl_to_lvds_in;
    output ecl_to_lvds_out_n;
    output ecl_to_lvds_out_p;
    input ecl_to_nim_in;
    output ecl_to_nim_out;
    input ecl_to_ttl_in;
    output ecl_to_ttl_out;
    input lvds_to_ecl_in_n;
    input lvds_to_ecl_in_p;
    output lvds_to_ecl_out;
    input nim_to_ecl_in;
    output nim_to_ecl_out;
    input ttl_to_ecl_in;
    output ttl_to_ecl_out;


    initial
        begin
        end

endmodule
