// generated by newgenasym  Mon Aug  2 14:26:26 2010


module \10ep142  (clk0, \clk0* , clk1, \clk1* , d, mr, q, \q7* , \s-in , \s-in* , sel);
    input clk0;
    input \clk0* ;
    input clk1;
    input \clk1* ;
    input [8:0] d;
    input mr;
    output [8:0] q;
    output \q7* ;
    input \s-in ;
    input \s-in* ;
    input sel;


    initial
        begin
        end

endmodule
