-- generated by newgenasym Mon Aug  2 14:26:26 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10ep142\ is
    port (    
	CLK0:      IN     STD_LOGIC;    
	\clk0*\:   IN     STD_LOGIC;    
	CLK1:      IN     STD_LOGIC;    
	\clk1*\:   IN     STD_LOGIC;    
	D:         IN     STD_LOGIC_VECTOR (8 DOWNTO 0);    
	MR:        IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (8 DOWNTO 0);    
	\q7*\:     OUT    STD_LOGIC;    
	\s-in\:    IN     STD_LOGIC;    
	\s-in*\:   IN     STD_LOGIC;    
	SEL:       IN     STD_LOGIC);
end \10ep142\;
