// generated by newgenasym  Tue Feb 15 14:58:15 2011


module lm1117 (ground, \input , \output );
    inout ground;
    input \input ;
    output \output ;


    initial
        begin
        end

endmodule
