// generated by newgenasym  Tue May 19 16:36:07 2015


module lm1117 (ground, \input , \output , output_2);
    inout ground;
    input \input ;
    output \output ;
    output output_2;


    initial
        begin
        end

endmodule
