-- generated by newgenasym Tue Feb 15 14:58:15 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM1117 is
    port (    
	GROUND:    INOUT  STD_LOGIC;    
	INPUT:     IN     STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC);
end LM1117;
