-- generated by newgenasym Tue May 19 16:36:07 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm1117 is
    port (    
	GROUND:    INOUT  STD_LOGIC;    
	INPUT:     IN     STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC;    
	OUTPUT_2:  OUT    STD_LOGIC);
end lm1117;
