// generated by newgenasym  Thu Mar 05 15:16:05 2015


module gt_delays (clk, data, ddgt_n, ddgt_p, dgt2, dgt_n, dgt_p, gt_ttl, le);
    input clk;
    input data;
    output ddgt_n;
    output ddgt_p;
    output dgt2;
    output dgt_n;
    output dgt_p;
    input gt_ttl;
    input le;


    initial
        begin
        end

endmodule
