// generated by newgenasym  Sat Feb 28 01:40:09 2015


module gt_delays (clk, data, ddgt_n, ddgt_p, dgt_n, dgt_p, gt_ttl, le);
    input clk;
    input data;
    output ddgt_n;
    output ddgt_p;
    output dgt_n;
    output dgt_p;
    input gt_ttl;
    input le;


    initial
        begin
        end

endmodule
