-- generated by newgenasym Sat Feb 28 01:40:09 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity gt_delays is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DDGT_N:    OUT    STD_LOGIC;    
	DDGT_P:    OUT    STD_LOGIC;    
	DGT_N:     OUT    STD_LOGIC;    
	DGT_P:     OUT    STD_LOGIC;    
	GT_TTL:    IN     STD_LOGIC;    
	LE:        IN     STD_LOGIC);
end gt_delays;
