// generated by newgenasym  Thu Jan 08 17:49:10 2015


module ds1023200 (\clk/p1 , \d/p2 , in, \le* , ms, out, p3, p4, p5, p6, p7, ps, pwm, \q/p0 );
    input \clk/p1 ;
    input \d/p2 ;
    input in;
    input \le* ;
    input ms;
    output out;
    input p3;
    input p4;
    input p5;
    input p6;
    input p7;
    input ps;
    output pwm;
    input \q/p0 ;


    initial
        begin
        end

endmodule
