-- generated by newgenasym Thu Jan 08 17:49:10 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds1023200 is
    port (    
	\clk/p1\:  IN     STD_LOGIC;    
	\d/p2\:    IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\le*\:     IN     STD_LOGIC;    
	MS:        IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	P3:        IN     STD_LOGIC;    
	P4:        IN     STD_LOGIC;    
	P5:        IN     STD_LOGIC;    
	P6:        IN     STD_LOGIC;    
	P7:        IN     STD_LOGIC;    
	PS:        IN     STD_LOGIC;    
	PWM:       OUT    STD_LOGIC;    
	\q/p0\:    IN     STD_LOGIC);
end ds1023200;
