// generated by newgenasym  Wed Jul 16 14:58:22 2014


module f74 (cl, cp, d, pr, q, \q* );
    input cl;
    input cp;
    input d;
    input pr;
    output q;
    output \q* ;


    initial
        begin
        end

endmodule
