-- generated by newgenasym Wed Jul 16 14:58:22 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity f74 is
    port (    
	CL:        IN     STD_LOGIC;    
	CP:        IN     STD_LOGIC;    
	D:         IN     STD_LOGIC;    
	PR:        IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC);
end f74;
