-- generated by newgenasym Mon Jan 26 12:38:30 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lvds_driver_ds10 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\in+\:     IN     STD_LOGIC;    
	\in-\:     IN     STD_LOGIC;    
	\out+\:    OUT    STD_LOGIC;    
	\out-\:    OUT    STD_LOGIC);
end lvds_driver_ds10;
