// generated by newgenasym  Tue Oct 07 16:09:43 2014


module adg1208 (a, d, en, s);
    input [2:0] a;
    output d;
    input en;
    inout [7:0] s;


    initial
        begin
        end

endmodule
