-- generated by newgenasym Tue Oct 07 16:09:43 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adg1208 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (2 DOWNTO 0);    
	D:         OUT    STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	S:         INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0));
end adg1208;
