// generated by newgenasym  Wed Mar 18 18:31:10 2015


module foxclock (ed, gnd, out, \out* , vdd);
    input ed;
    input gnd;
    output out;
    output \out* ;
    input vdd;


    initial
        begin
        end

endmodule
