// generated by newgenasym  Tue Nov 11 17:24:53 2014


module foxclock (ed, nc, out, \out* );
    input ed;
    inout nc;
    output out;
    output \out* ;


    initial
        begin
        end

endmodule
