-- generated by newgenasym Tue Nov 11 17:24:53 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity foxclock is
    port (    
	ED:        IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	\out*\:    OUT    STD_LOGIC);
end foxclock;
