-- generated by newgenasym Tue May 18 12:03:00 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM337T_L is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC;    
	REF:       INOUT  STD_LOGIC);
end LM337T_L;
