// Generated by Part Developer

// Modified to support swift models
`timescale 1ns/100ps

module hct04 (\y* ,a);
	parameter   size = 1;
	output [size-1:0] \y* ;
	input [size-1:0] a;




	SIG74hct04P inst1 [size-1:0] 
		(
		a,
		\y* 
		);



endmodule

