-- generated by newgenasym Sat May 16 16:12:37 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ostoq027150 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ostoq027150;
