// generated by newgenasym  Thu Apr 07 17:24:22 2011


module \100el05  (in1, \in1* , in2, \in2* , out, \out* );
    input in1;
    input \in1* ;
    input in2;
    input \in2* ;
    output out;
    output \out* ;


    initial
        begin
        end

endmodule
