-- generated by newgenasym Thu Apr 07 17:24:22 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \100el05\ is
    port (    
	IN1:       IN     STD_LOGIC;    
	\in1*\:    IN     STD_LOGIC;    
	IN2:       IN     STD_LOGIC;    
	\in2*\:    IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	\out*\:    OUT    STD_LOGIC);
end \100el05\;
