-- generated by newgenasym Tue Aug 19 10:27:45 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1n4448\ is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end \1n4448\;
