// generated by newgenasym  Tue May 19 16:53:11 2015


module \7915s_l  (ground, \input , \output , output_2);
    inout ground;
    input \input ;
    output \output ;
    inout output_2;


    initial
        begin
        end

endmodule
