-- generated by newgenasym Tue May 19 16:53:11 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \7915s_l\ is
    port (    
	GROUND:    INOUT  STD_LOGIC;    
	INPUT:     IN     STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC;    
	OUTPUT_2:  INOUT  STD_LOGIC);
end \7915s_l\;
