// generated by newgenasym  Tue Nov 04 11:56:15 2014


module prma1c05b (ctrl_in, ctrl_out, in, in_cpy, out1, out2);
    inout ctrl_in;
    inout ctrl_out;
    inout in;
    inout in_cpy;
    inout out1;
    inout out2;


    initial
        begin
        end

endmodule
