-- generated by newgenasym Tue Nov 04 11:56:15 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity prma1c05b is
    port (    
	CTRL_IN:   INOUT  STD_LOGIC;    
	CTRL_OUT:  INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	IN_CPY:    INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC);
end prma1c05b;
