// generated by newgenasym  Sat Feb 28 19:00:43 2015


module ecal_control (ecal_active, ext_ped_in, ext_ped_out, gt);
    input ecal_active;
    input ext_ped_in;
    output ext_ped_out;
    input gt;


    initial
        begin
        end

endmodule
