-- generated by newgenasym Sat Feb 28 19:00:43 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ecal_control is
    port (    
	ECAL_ACTIVE: IN     STD_LOGIC;    
	EXT_PED_IN: IN     STD_LOGIC;    
	EXT_PED_OUT: OUT    STD_LOGIC;    
	GT:        IN     STD_LOGIC);
end ecal_control;
