-- generated by newgenasym Wed Jul 16 15:49:22 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \100el34\ is
    port (    
	CLK:       IN     STD_LOGIC;    
	\clk*\:    IN     STD_LOGIC;    
	\en*\:     IN     STD_LOGIC;    
	MR:        IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	OUT2:      OUT    STD_LOGIC;    
	\out2*\:   OUT    STD_LOGIC;    
	OUT4:      OUT    STD_LOGIC;    
	\out4*\:   OUT    STD_LOGIC;    
	OUT8:      OUT    STD_LOGIC;    
	\out8*\:   OUT    STD_LOGIC;    
	VBB:       IN     STD_LOGIC);
end \100el34\;
