// generated by newgenasym  Wed Jul 16 15:07:13 2014


module f269 (cep, cet, cp, p, pe, q, tc, \u/d );
    input cep;
    input cet;
    input cp;
    input [7:0] p;
    input pe;
    output [7:0] q;
    output tc;
    input \u/d ;


    initial
        begin
        end

endmodule
