-- generated by newgenasym Wed Jul 16 15:07:13 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity f269 is
    port (    
	CEP:       IN     STD_LOGIC;    
	CET:       IN     STD_LOGIC;    
	CP:        IN     STD_LOGIC;    
	P:         IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	PE:        IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	TC:        OUT    STD_LOGIC;    
	\u/d\:     IN     STD_LOGIC);
end f269;
