-- generated by newgenasym Thu Aug 12 11:34:28 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsmd0805 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end rsmd0805;
