-- generated by newgenasym Tue May 18 12:01:37 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \7815s_l\ is
    port (    
	GROUND:    INOUT  STD_LOGIC;    
	INPUT:     IN     STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC);
end \7815s_l\;
