// generated by newgenasym  Sat Mar 07 16:54:33 2015


module ext_trig_ports (ext_ped_in, ext_ped_out, ext_trig_in, tubii_rt_out);
    output ext_ped_in;
    input ext_ped_out;
    output [0:15] ext_trig_in;
    input tubii_rt_out;


    initial
        begin
        end

endmodule
