-- generated by newgenasym Sat Mar 07 16:54:33 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ext_trig_ports is
    port (    
	EXT_PED_IN: OUT    STD_LOGIC;    
	EXT_PED_OUT: IN     STD_LOGIC;    
	EXT_TRIG_IN: OUT    STD_LOGIC_VECTOR (0 TO 15);    
	TUBII_RT_OUT: IN     STD_LOGIC);
end ext_trig_ports;
