-- generated by newgenasym Thu May 28 17:05:55 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1n5822\ is
    port (    
	AN:        INOUT  STD_LOGIC;    
	CAT:       INOUT  STD_LOGIC);
end \1n5822\;
