-- generated by newgenasym Thu Jun 04 15:06:30 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1n5822\ is
    port (    
	AN:        INOUT  STD_LOGIC;    
	CAT:       INOUT  STD_LOGIC);
end \1n5822\;
