// generated by chdl_uprev Sat Sep 13 01:37:17 1997

// Modified to support swift models
`timescale 1ns/100ps

module \10h125  (a, \b* , v, y);
    parameter    size = 1;
    parameter    ModelType = "SWIFT";
    parameter    TimingVersion = "MC10H125";
    parameter    DelayRange = "max";
    parameter    MemoryFile = "memory";
    input [size-1:0] a;
    input [size-1:0] \b* ;
    output [size-1:0] y;
    output v;


    ecl25 #(ModelType, TimingVersion, DelayRange, MemoryFile)  inst1[size-1:0] (.AIN(a),
                               .AINN(\b* ),
                               .AOUT(y) );
endmodule
