-- generated by newgenasym Tue May 18 12:02:58 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM337S_L is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC;    
	REF:       INOUT  STD_LOGIC);
end LM337S_L;
