// generated by newgenasym  Sat Mar 07 23:06:20 2015


module mc10h116 (d1, \d1* , d2, \d2* , d3, \d3* , gnd1, gnd2, q1, \q1* , q2, \q2* , q3, \q3* ,
        vbb, vee);
    input d1;
    input \d1* ;
    input d2;
    input \d2* ;
    input d3;
    input \d3* ;
    input gnd1;
    input gnd2;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    output q3;
    output \q3* ;
    output vbb;
    input vee;


    initial
        begin
        end

endmodule
