// generated by newgenasym  Sat Feb 28 19:29:36 2015


module mc10h116 (d1, \d1* , d2, \d2* , d3, \d3* , gnd1, gnd2, q1, \q1* , q2, \q2* , q3, \q3* ,
        vbb, vee);
    input d1;
    input \d1* ;
    input d2;
    input \d2* ;
    input d3;
    input \d3* ;
    inout gnd1;
    inout gnd2;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    output q3;
    output \q3* ;
    inout vbb;
    inout vee;


    initial
        begin
        end

endmodule
