-- generated by newgenasym Sat Mar 07 19:30:17 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc10h116 is
    port (    
	D1:        IN     STD_LOGIC;    
	\d1*\:     IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	\d2*\:     IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	\d3*\:     IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	\q1*\:     OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	\q2*\:     OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	\q3*\:     OUT    STD_LOGIC;    
	VBB:       OUT    STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end mc10h116;
