// generated by newgenasym  Fri Sep 17 14:15:51 2010


module \74f14  (i0, i1, i2, i3, i4, i5, \o0* , \o1* , \o2* , \o3* , \o4* , \o5* );
    input i0;
    input i1;
    input i2;
    input i3;
    input i4;
    input i5;
    input \o0* ;
    input \o1* ;
    input \o2* ;
    input \o3* ;
    input \o4* ;
    input \o5* ;


    initial
        begin
        end

endmodule
