-- generated by newgenasym Fri Sep 17 14:15:51 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74f14\ is
    port (    
	I0:        IN     STD_LOGIC;    
	I1:        IN     STD_LOGIC;    
	I2:        IN     STD_LOGIC;    
	I3:        IN     STD_LOGIC;    
	I4:        IN     STD_LOGIC;    
	I5:        IN     STD_LOGIC;    
	\o0*\:     IN     STD_LOGIC;    
	\o1*\:     IN     STD_LOGIC;    
	\o2*\:     IN     STD_LOGIC;    
	\o3*\:     IN     STD_LOGIC;    
	\o4*\:     IN     STD_LOGIC;    
	\o5*\:     IN     STD_LOGIC);
end \74f14\;
