// generated by newgenasym  Fri Jul 30 19:05:30 2010


module \10e104  (a0, a1, a2, a3, a4, b0, b1, b2, b3, b4, f, \f* , y0, \y0* , y1, \y1* , y2,
        \y2* , y3, \y3* , y4, \y4* );
    parameter    size = 1;
    input [size-1:0] a0;
    input [size-1:0] a1;
    input [size-1:0] a2;
    input [size-1:0] a3;
    input [size-1:0] a4;
    input [size-1:0] b0;
    input [size-1:0] b1;
    input [size-1:0] b2;
    input [size-1:0] b3;
    input [size-1:0] b4;
    output [size-1:0] f;
    output [size-1:0] \f* ;
    output [size-1:0] y0;
    output [size-1:0] \y0* ;
    output [size-1:0] y1;
    output [size-1:0] \y1* ;
    output [size-1:0] y2;
    output [size-1:0] \y2* ;
    output [size-1:0] y3;
    output [size-1:0] \y3* ;
    output [size-1:0] y4;
    output [size-1:0] \y4* ;


    initial
        begin
        end

endmodule
