-- generated by newgenasym Fri Jul 30 19:05:30 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10e104\ is
    generic (
        size:positive:= 1
            );
    port (    
	A0:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	A1:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	A2:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	A3:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	A4:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B0:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B1:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B2:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B3:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B4:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	F:         OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\f*\:      OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Y0:        OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y0*\:     OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Y1:        OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y1*\:     OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Y2:        OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y2*\:     OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Y3:        OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y3*\:     OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Y4:        OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y4*\:     OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \10e104\;
