// generated by newgenasym  Tue Feb  8 12:24:07 2011


module smbconn (pin1, pin3, pin5, pin7, pin9);
    inout pin1;
    input pin3;
    input pin5;
    input pin7;
    input pin9;


    initial
        begin
        end

endmodule
