-- generated by newgenasym Tue Feb  8 12:24:07 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SMBCONN is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN3:      IN     STD_LOGIC;    
	PIN5:      IN     STD_LOGIC;    
	PIN7:      IN     STD_LOGIC;    
	PIN9:      IN     STD_LOGIC);
end SMBCONN;
