-- generated by newgenasym Tue May 18 12:00:45 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CONN_GEN is
    generic (
        size:positive:= 1
            );
    port (    
	CON_PIN:   INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end CONN_GEN;
