// generated by newgenasym  Wed Aug 25 17:20:01 2010


module as12av (nc1, nc2, nc3, nc4, nc5, nc6, outa, outb, vneg, vpos);
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout outa;
    inout outb;
    inout vneg;
    inout vpos;


    initial
        begin
        end

endmodule
