-- generated by newgenasym Wed Aug 25 17:20:01 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity as12av is
    port (    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	NC6:       INOUT  STD_LOGIC;    
	OUTA:      INOUT  STD_LOGIC;    
	OUTB:      INOUT  STD_LOGIC;    
	VNEG:      INOUT  STD_LOGIC;    
	VPOS:      INOUT  STD_LOGIC);
end as12av;
