-- generated by newgenasym Tue Apr 05 20:13:50 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mmbth10 is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end mmbth10;
