// generated by newgenasym  Wed Oct 29 14:26:37 2014


module f06 (a, a0, a1, a2, a3, a4, a5, \y* , \y0* , \y1* , \y2* , \y3* , \y4* , \y5* );
    parameter    max_delay = 10000;
    parameter    size = 1;
    input [size-1:0] a;
    input a0;
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    output [size-1:0] \y* ;
    output \y0* ;
    output \y1* ;
    output \y2* ;
    output \y3* ;
    output \y4* ;
    output \y5* ;


    initial
        begin
        end

endmodule
