-- generated by newgenasym Wed Oct 29 14:26:38 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity f06 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y0*\:     OUT    STD_LOGIC;    
	\y1*\:     OUT    STD_LOGIC;    
	\y2*\:     OUT    STD_LOGIC;    
	\y3*\:     OUT    STD_LOGIC;    
	\y4*\:     OUT    STD_LOGIC;    
	\y5*\:     OUT    STD_LOGIC);
end f06;
