// generated by newgenasym  Tue May 18 12:04:56 2010


module lm309h_l (an, cat, gnd, ref);
    input an;
    output cat;
    inout gnd;
    inout ref;


    initial
        begin
        end

endmodule
