-- generated by newgenasym Tue May 18 12:04:56 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM309H_L is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC);
end LM309H_L;
