// generated by newgenasym  Sat Mar 07 19:14:49 2015


module ext_trigs (ext_trig_in, ext_trig_out);
    input [0:15] ext_trig_in;
    output [0:15] ext_trig_out;


    initial
        begin
        end

endmodule
