// generated by newgenasym  Thu Mar 05 18:01:06 2015


module ext_trigs (ext_trig_in, ext_trig_out);
    input [0:15] ext_trig_in;
    input [0:15] ext_trig_out;


    initial
        begin
        end

endmodule
