-- generated by newgenasym Thu Mar 05 18:01:06 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ext_trigs is
    port (    
	EXT_TRIG_IN: IN     STD_LOGIC_VECTOR (0 TO 15);    
	EXT_TRIG_OUT: IN     STD_LOGIC_VECTOR (0 TO 15));
end ext_trigs;
