-- generated by newgenasym Sat Mar 07 19:14:49 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ext_trigs is
    port (    
	EXT_TRIG_IN: IN     STD_LOGIC_VECTOR (0 TO 15);    
	EXT_TRIG_OUT: OUT    STD_LOGIC_VECTOR (0 TO 15));
end ext_trigs;
