// generated by newgenasym  Fri Mar 06 18:03:03 2015


module time_bus_ports (gt_n, gt_p, sync24_n, sync24_p, sync_n, sync_p);
    output gt_n;
    output gt_p;
    output sync24_n;
    output sync24_p;
    output sync_n;
    output sync_p;


    initial
        begin
        end

endmodule
