-- generated by newgenasym Fri Mar 06 18:03:03 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity time_bus_ports is
    port (    
	GT_N:      OUT    STD_LOGIC;    
	GT_P:      OUT    STD_LOGIC;    
	SYNC24_N:  OUT    STD_LOGIC;    
	SYNC24_P:  OUT    STD_LOGIC;    
	SYNC_N:    OUT    STD_LOGIC;    
	SYNC_P:    OUT    STD_LOGIC);
end time_bus_ports;
