// generated by chdl_uprev Thu Sep  4 17:25:24 1997

`timescale 1ns/100ps

module \10e016  (\ce* , clk, mr, p, \pe* , q, \tc* , tcld);
    input [7:0] p;
    input tcld;
    input \ce* ;
    input clk;
    input \pe* ;
    input mr;
    output [7:0] q;
    output \tc* ;


    MC10E016  inst1 (/*.vee(unconnected)*/,
                               /*.NC(unconnected)*/,
                               /*.P0*/ p[0],
                               /*.P1*/ p[1],
                               /*.P2*/ p[2],
                               /*.P3*/ p[3],
                               /*.P4*/ p[4],
                               /*.gnd2(unconnected)*/,
                               /*.Q0*/ q[0],
                               /*.Q1*/ q[1],
                               /*.Q2*/ q[2],
                               /*.Q3*/ q[3],
                               /*.Q4*/ q[4],
                               /*.gnd2(unconnected)*/,
                               /*.Q5*/ q[5],
                               /*.gnd1(unconnected)*/,
                               /*.Q6*/ q[6],
                               /*.Q7*/ q[7],
                               /*.TC_*/ \tc* ,
                               /*.gnd2(unconnected)*/,
                               /*.P5*/ p[5],
                               /*.P6*/ p[6],
                               /*.P7*/ p[7],
                               /*.CE_*/ \ce* ,
                               /*.PE_*/ \pe* ,
                               /*.MR*/ mr,
                               /*.CLK*/ clk,
                               /*.TCLD*/ tcld );
endmodule
