// generated by newgenasym  Wed Oct 22 11:15:01 2014


module opa277 (\in+ , \in- , out, trim_a, trim_b, \v+ , \v- );
    inout \in+ ;
    inout \in- ;
    inout out;
    inout trim_a;
    inout trim_b;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
