// generated by newgenasym  Fri Sep 05 13:23:15 2014


module \74f164  (cp, dsa, dsb, \mr* , q, q0, q1, q2, q3, q4, q5, q6, q7);
    input cp;
    input dsa;
    input dsb;
    input \mr* ;
    output [7:0] q;
    output q0;
    output q1;
    output q2;
    output q3;
    output q4;
    output q5;
    output q6;
    output q7;


    initial
        begin
        end

endmodule
