-- generated by newgenasym Fri Sep 05 13:23:15 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74f164\ is
    port (    
	CP:        IN     STD_LOGIC;    
	DSA:       IN     STD_LOGIC;    
	DSB:       IN     STD_LOGIC;    
	\mr*\:     IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	Q5:        OUT    STD_LOGIC;    
	Q6:        OUT    STD_LOGIC;    
	Q7:        OUT    STD_LOGIC);
end \74f164\;
