// generated by newgenasym  Tue Oct 14 11:15:30 2014


module \74hct165  (\ce* , cp, d0, d1, d2, d3, d4, d5, d6, d7, ds, \pl* , q7, \q7* );
    input \ce* ;
    input cp;
    input d0;
    input d1;
    input d2;
    input d3;
    input d4;
    input d5;
    input d6;
    input d7;
    input ds;
    input \pl* ;
    output q7;
    output \q7* ;


    initial
        begin
        end

endmodule
