// generated by newgenasym  Sat Feb 28 13:30:58 2015


module \74hct165  (\ce* , cp, d0, d1, d2, d3, d4, d5, d6, d7, ds, gnd, \pl* , q7, \q7* , vcc);
    input \ce* ;
    input cp;
    input d0;
    input d1;
    input d2;
    input d3;
    input d4;
    input d5;
    input d6;
    input d7;
    input ds;
    input gnd;
    input \pl* ;
    output q7;
    output \q7* ;
    input vcc;


    initial
        begin
        end

endmodule
