-- generated by newgenasym Tue Oct 14 11:15:30 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hct165\ is
    port (    
	\ce*\:     IN     STD_LOGIC;    
	CP:        IN     STD_LOGIC;    
	D0:        IN     STD_LOGIC;    
	D1:        IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	D5:        IN     STD_LOGIC;    
	D6:        IN     STD_LOGIC;    
	D7:        IN     STD_LOGIC;    
	DS:        IN     STD_LOGIC;    
	\pl*\:     IN     STD_LOGIC;    
	Q7:        OUT    STD_LOGIC;    
	\q7*\:     OUT    STD_LOGIC);
end \74hct165\;
