// generated by newgenasym  Sun Mar 01 14:33:02 2015


module sy100el91l (d0, \d0* , d1, \d1* , d2, \d2* , gnd0, gnd1, pecl_vbb0, pecl_vbb1,
        q0, \q0* , q1, \q1* , q2, \q2* , vcc0, vcc1, vcc2, vee);
    input d0;
    input \d0* ;
    input d1;
    input \d1* ;
    input d2;
    input \d2* ;
    input gnd0;
    input gnd1;
    output pecl_vbb0;
    output pecl_vbb1;
    output q0;
    output \q0* ;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    input vcc0;
    input vcc1;
    input vcc2;
    input vee;


    initial
        begin
        end

endmodule
