-- generated by newgenasym Sun Mar 01 15:35:05 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sy100el91l is
    port (    
	D0:        IN     STD_LOGIC;    
	\d0*\:     IN     STD_LOGIC;    
	D1:        IN     STD_LOGIC;    
	\d1*\:     IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	\d2*\:     IN     STD_LOGIC;    
	GND0:      IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	PECL_VBB0: OUT    STD_LOGIC;    
	PECL_VBB1: OUT    STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	\q0*\:     OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	\q1*\:     OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	\q2*\:     OUT    STD_LOGIC;    
	VCC0:      IN     STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end sy100el91l;
