// generated by newgenasym  Fri Mar 06 17:55:51 2015


module clock_ports (clk100_n, clk100_p, tub_clk_in);
    input clk100_n;
    input clk100_p;
    output tub_clk_in;


    initial
        begin
        end

endmodule
