-- generated by newgenasym Fri Mar 06 17:55:51 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity clock_ports is
    port (    
	CLK100_N:  IN     STD_LOGIC;    
	CLK100_P:  IN     STD_LOGIC;    
	TUB_CLK_IN: OUT    STD_LOGIC);
end clock_ports;
