-- generated by newgenasym Mon Sep 13 10:48:35 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \200-1-c-53d\ is
    port (    
	C:         OUT    STD_LOGIC;    
	CI:        INOUT  STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	O:         OUT    STD_LOGIC);
end \200-1-c-53d\;
