-- generated by newgenasym Mon Sep 13 13:54:04 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ep12sd1sape is
    port (    
	CLOSED:    OUT    STD_LOGIC;    
	COMM:      IN     STD_LOGIC;    
	\open\:    OUT    STD_LOGIC);
end ep12sd1sape;
