// generated by newgenasym  Thu Jan 29 11:49:48 2015


module sip_header_16pin (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \15 ;
    inout \16 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;


    initial
        begin
        end

endmodule
