// generated by newgenasym  Mon Sep 13 13:49:04 2010


module inductor_l (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
