// generated by newgenasym  Thu May 28 13:48:47 2015


module inductor_l (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
