-- generated by newgenasym Thu May 28 13:48:47 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity inductor_l is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end inductor_l;
