// generated by newgenasym  Sat Feb 28 14:14:44 2015


module cntrl_register (clk, data, data_rdy, default_clk_sel, display,
        ecal_enable, le, lo_sel, read_bit, reg_val);
    input clk;
    input data;
    input data_rdy;
    output default_clk_sel;
    output [1:3] display;
    output ecal_enable;
    input le;
    output lo_sel;
    input read_bit;
    output reg_val;


    initial
        begin
        end

endmodule
