// generated by newgenasym  Fri Feb 27 22:27:28 2015


module cntrl_register (clk, data, le, read_bit);
    input clk;
    input data;
    input le;
    input read_bit;


    initial
        begin
        end

endmodule
