-- generated by newgenasym Fri Feb 27 22:27:28 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cntrl_register is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	READ_BIT:  IN     STD_LOGIC);
end cntrl_register;
