-- generated by newgenasym Sat Feb 28 14:14:44 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cntrl_register is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	DEFAULT_CLK_SEL: OUT    STD_LOGIC;    
	DISPLAY:   OUT    STD_LOGIC_VECTOR (1 TO 3);    
	ECAL_ENABLE: OUT    STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	LO_SEL:    OUT    STD_LOGIC;    
	READ_BIT:  IN     STD_LOGIC;    
	REG_VAL:   OUT    STD_LOGIC);
end cntrl_register;
