-- generated by newgenasym Fri May 02 12:06:25 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bss138 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end bss138;
