// generated by newgenasym  Thu Mar 05 18:34:31 2015


module microzed_module (caen_data_rdy, clk, clk100_in, clocks_data_rdy,
        cntrl_rdy, cntrl_reg_chk, data, ext_trig,
        generic_delay_in, generic_delay_out, generic_pulse, le,
        mtca_mimic_data_rdy, read_cntrl_reg_bit, spkr);
    output caen_data_rdy;
    output clk;
    input clk100_in;
    output clocks_data_rdy;
    output cntrl_rdy;
    input cntrl_reg_chk;
    output data;
    input [0:15] ext_trig;
    input generic_delay_in;
    output generic_delay_out;
    output generic_pulse;
    output [2:0] le;
    output mtca_mimic_data_rdy;
    output read_cntrl_reg_bit;
    output spkr;


    initial
        begin
        end

endmodule
