// generated by newgenasym  Sat Mar 07 16:54:41 2015


module microzed_module (caen_data_rdy, clk, clk100_in, clocks_data_rdy,
        cntrl_rdy, cntrl_reg_chk, data, ext_trig,
        generic_delay_in, generic_delay_out, generic_pulse, gt,
        le, mtca_mimic_data_rdy, read_cntrl_reg_bit, scaler,
        smellie_delay, smellie_pre_delay, smellie_pulse, spkr,
        sync, sync24, tellie_delay, tellie_pre_delay,
        tellie_pulse, tubii_rt_out);
    output caen_data_rdy;
    output clk;
    input clk100_in;
    output clocks_data_rdy;
    output cntrl_rdy;
    input cntrl_reg_chk;
    output data;
    input [0:15] ext_trig;
    input generic_delay_in;
    output generic_delay_out;
    output generic_pulse;
    input gt;
    output [2:0] le;
    output mtca_mimic_data_rdy;
    output read_cntrl_reg_bit;
    output [4:6] scaler;
    output smellie_delay;
    input smellie_pre_delay;
    output smellie_pulse;
    output spkr;
    input sync;
    input sync24;
    output tellie_delay;
    input tellie_pre_delay;
    output tellie_pulse;
    output tubii_rt_out;


    initial
        begin
        end

endmodule
