// generated by newgenasym  Thu Mar 05 13:16:51 2015


module microzed_module (clk, data, generic_delay_in, generic_delay_out,
        generic_pulse, le);
    output clk;
    output data;
    input generic_delay_in;
    output generic_delay_out;
    output generic_pulse;
    output [0:2] le;


    initial
        begin
        end

endmodule
