-- generated by newgenasym Thu Mar 05 13:16:51 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity microzed_module is
    port (    
	CLK:       OUT    STD_LOGIC;    
	DATA:      OUT    STD_LOGIC;    
	GENERIC_DELAY_IN: IN     STD_LOGIC;    
	GENERIC_DELAY_OUT: OUT    STD_LOGIC;    
	GENERIC_PULSE: OUT    STD_LOGIC;    
	LE:        OUT    STD_LOGIC_VECTOR (0 TO 2));
end microzed_module;
