// generated by newgenasym  Sat Mar 07 18:51:14 2015


module clocks (bckp_used, clk100_n, clk100_p, clk100_ttl, clk_sel, data,
        data_rdy, le, reset, sr_clk, tub_clk_in);
    output bckp_used;
    output clk100_n;
    output clk100_p;
    output clk100_ttl;
    input clk_sel;
    input data;
    input data_rdy;
    input le;
    input reset;
    input sr_clk;
    input tub_clk_in;


    initial
        begin
        end

endmodule
