// generated by newgenasym  Thu Mar 05 18:00:51 2015


module clocks (clk100_p, clk100_ttl, clk_100_n, clk_sel, data_rdy,
        tub_clk_in);
    output clk100_p;
    output clk100_ttl;
    output clk_100_n;
    input clk_sel;
    input data_rdy;
    output tub_clk_in;


    initial
        begin
        end

endmodule
