// generated by newgenasym  Tue Mar 03 19:18:28 2015


module clocks (clk100_p, clk100_ttl, clk_100_n, tub_clk_in);
    output clk100_p;
    output clk100_ttl;
    output clk_100_n;
    output tub_clk_in;


    initial
        begin
        end

endmodule
