-- generated by newgenasym Thu Mar 05 18:00:51 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity clocks is
    port (    
	CLK100_P:  OUT    STD_LOGIC;    
	CLK100_TTL: OUT    STD_LOGIC;    
	CLK_100_N: OUT    STD_LOGIC;    
	CLK_SEL:   IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	TUB_CLK_IN: OUT    STD_LOGIC);
end clocks;
