-- generated by newgenasym Tue Mar 03 19:18:28 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity clocks is
    port (    
	CLK100_P:  OUT    STD_LOGIC;    
	CLK100_TTL: OUT    STD_LOGIC;    
	CLK_100_N: OUT    STD_LOGIC;    
	TUB_CLK_IN: OUT    STD_LOGIC);
end clocks;
