// generated by genview  Fri Jan 16 22:43:15 1998

`timescale 1ns/100ps

module \10e101  (a, b, c, d, y, \y* );
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] b;
    input [size-1:0] c;
    input [size-1:0] d;
    output [size-1:0] y;
    output [size-1:0] \y* ;


    MC10E101P  inst1[size-1:0] (/*.D0D*/ d,
                               /*.D0C*/ c,
                               /*.D0B*/ b,
                               /*.D0A*/ a,
                               /*.Q0*/ y,
                               /*.Q0_*/ \y*  );
endmodule