-- generated by newgenasym Thu Jan 29 11:19:37 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ss12sdp2 is
    port (    
	P:         INOUT  STD_LOGIC;    
	T_A:       INOUT  STD_LOGIC;    
	T_B:       INOUT  STD_LOGIC);
end ss12sdp2;
