// generated by newgenasym  Fri Apr 08 09:47:45 2011


module \100e101  (d0, d1, d2, d3, q, \q* );
    input d0;
    input d1;
    input d2;
    input d3;
    output q;
    output \q* ;


    initial
        begin
        end

endmodule
