-- generated by newgenasym Fri Apr 08 09:47:45 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \100e101\ is
    port (    
	D0:        IN     STD_LOGIC;    
	D1:        IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC);
end \100e101\;
