-- generated by newgenasym Thu Mar 05 12:44:02 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity front_ports is
    port (    
	ECL_TO_LVDS_IN: OUT    STD_LOGIC;    
	ECL_TO_LVDS_OUT_N: IN     STD_LOGIC;    
	ECL_TO_LVDS_OUT_P: IN     STD_LOGIC;    
	ECL_TO_NIM_IN: OUT    STD_LOGIC;    
	ECL_TO_NIM_OUT: IN     STD_LOGIC;    
	ECL_TO_TTL_IN: OUT    STD_LOGIC;    
	ECL_TO_TTL_OUT: IN     STD_LOGIC;    
	LVDS_TO_ECL_IN_N: OUT    STD_LOGIC;    
	LVDS_TO_ECL_IN_P: OUT    STD_LOGIC;    
	LVDS_TO_ECL_OUT: IN     STD_LOGIC;    
	NIM_TO_ECL_IN: OUT    STD_LOGIC;    
	NIM_TO_ECL_OUT: IN     STD_LOGIC;    
	TTL_TO_ECL_IN: OUT    STD_LOGIC;    
	TTL_TO_ECL_OUT: IN     STD_LOGIC);
end front_ports;
