// generated by newgenasym  Mon May 18 14:15:05 2015


module \74hct164  (cp, dsa, dsb, gnd, \mr* , q0, q1, q2, q3, q4, q5, q6, q7, vcc);
    input cp;
    input dsa;
    input dsb;
    input gnd;
    input \mr* ;
    output q0;
    output q1;
    output q2;
    output q3;
    output q4;
    output q5;
    output q6;
    output q7;
    input vcc;


    initial
        begin
        end

endmodule
