-- generated by newgenasym Mon May 18 14:03:44 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hct164\ is
    port (    
	CP:        IN     STD_LOGIC;    
	DSA:       IN     STD_LOGIC;    
	DSB:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\mr*\:     IN     STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	Q5:        OUT    STD_LOGIC;    
	Q6:        OUT    STD_LOGIC;    
	Q7:        OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end \74hct164\;
