// generated by newgenasym  Sat Mar 07 16:43:46 2015


module gt_delays_ports (dgt_n, dgt_p, lo_star_out_n, lo_star_out_p, \mtcd_lo* );
    input dgt_n;
    input dgt_p;
    input lo_star_out_n;
    input lo_star_out_p;
    output \mtcd_lo* ;


    initial
        begin
        end

endmodule
