-- generated by newgenasym Sat Mar 07 16:43:46 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity gt_delays_ports is
    port (    
	DGT_N:     IN     STD_LOGIC;    
	DGT_P:     IN     STD_LOGIC;    
	LO_STAR_OUT_N: IN     STD_LOGIC;    
	LO_STAR_OUT_P: IN     STD_LOGIC;    
	\mtcd_lo*\: OUT    STD_LOGIC);
end gt_delays_ports;
