-- generated by newgenasym Fri Oct 24 13:54:31 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity csmd0805 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end csmd0805;
