-- generated by newgenasym Mon Jul 14 17:35:55 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity f07 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Y:         OUT    STD_LOGIC);
end f07;
