-- generated by newgenasym Tue Aug 31 12:02:08 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74f07\ is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	Y0:        OUT    STD_LOGIC;    
	Y1:        OUT    STD_LOGIC;    
	Y2:        OUT    STD_LOGIC;    
	Y3:        OUT    STD_LOGIC;    
	Y4:        OUT    STD_LOGIC;    
	Y5:        OUT    STD_LOGIC);
end \74f07\;
