-- generated by newgenasym Fri Jan 30 18:31:33 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_l is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end led_l;
