-- generated by newgenasym Mon May 18 18:33:23 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity z4ke is
    port (    
	\and\:     INOUT  STD_LOGIC;    
	CAT:       INOUT  STD_LOGIC);
end z4ke;
