// generated by newgenasym  Thu Mar 05 19:38:55 2015


module ellie_coms (smellie_delay_out, smellie_delay_out_ttl,
        smellie_pre_delay_ecl, smellie_pre_delay_ttl,
        smellie_pulse, smellie_pulse_out, tellie_delay_out,
        tellie_delay_out_ttl, tellie_pre_delay_ecl,
        tellie_pre_delay_ttl, tellie_pulse, tellie_pulse_out);
    output smellie_delay_out;
    input smellie_delay_out_ttl;
    input smellie_pre_delay_ecl;
    output smellie_pre_delay_ttl;
    input smellie_pulse;
    output smellie_pulse_out;
    output tellie_delay_out;
    input tellie_delay_out_ttl;
    input tellie_pre_delay_ecl;
    output tellie_pre_delay_ttl;
    input tellie_pulse;
    output tellie_pulse_out;


    initial
        begin
        end

endmodule
