-- generated by newgenasym Thu Mar 05 19:38:55 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ellie_coms is
    port (    
	SMELLIE_DELAY_OUT: OUT    STD_LOGIC;    
	SMELLIE_DELAY_OUT_TTL: IN     STD_LOGIC;    
	SMELLIE_PRE_DELAY_ECL: IN     STD_LOGIC;    
	SMELLIE_PRE_DELAY_TTL: OUT    STD_LOGIC;    
	SMELLIE_PULSE: IN     STD_LOGIC;    
	SMELLIE_PULSE_OUT: OUT    STD_LOGIC;    
	TELLIE_DELAY_OUT: OUT    STD_LOGIC;    
	TELLIE_DELAY_OUT_TTL: IN     STD_LOGIC;    
	TELLIE_PRE_DELAY_ECL: IN     STD_LOGIC;    
	TELLIE_PRE_DELAY_TTL: OUT    STD_LOGIC;    
	TELLIE_PULSE: IN     STD_LOGIC;    
	TELLIE_PULSE_OUT: OUT    STD_LOGIC);
end ellie_coms;
