-- generated by newgenasym Tue May 18 12:00:47 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CTAP is
    port (    
	B:         IN     STD_LOGIC;    
	S:         OUT    STD_LOGIC);
end CTAP;
