// generated by newgenasym  Mon Sep 15 09:26:06 2014


module hct123 (c, \c/r , \cl* , clock, \clock* , q, \q* );
    parameter    pulse_width = 10000;
    inout c;
    inout \c/r ;
    input \cl* ;
    input clock;
    input \clock* ;
    output q;
    output \q* ;


    initial
        begin
        end

endmodule
