// generated by newgenasym  Sat Feb 28 01:24:52 2015


module hct123 (cext1, cext2, gnd, \in_a1* , \in_a2* , in_b1, in_b2, q1, \q1* , q2,
        \q2* , \rd1* , \rd2* , \rext/cext1 , \rext/cext2 , vcc);
    parameter    pulse_width = 10000;
    inout cext1;
    inout cext2;
    input gnd;
    input \in_a1* ;
    input \in_a2* ;
    input in_b1;
    input in_b2;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    input \rd1* ;
    input \rd2* ;
    inout \rext/cext1 ;
    inout \rext/cext2 ;
    input vcc;


    initial
        begin
        end

endmodule
