-- generated by newgenasym Sat Mar 07 22:28:59 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hct123 is
    port (    
	CEXT1:     INOUT  STD_LOGIC;    
	CEXT2:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in_a1*\:  IN     STD_LOGIC;    
	\in_a2*\:  IN     STD_LOGIC;    
	IN_B1:     IN     STD_LOGIC;    
	IN_B2:     IN     STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	\q1*\:     OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	\q2*\:     OUT    STD_LOGIC;    
	\rd1*\:    IN     STD_LOGIC;    
	\rd2*\:    IN     STD_LOGIC;    
	\rext/cext1\: INOUT  STD_LOGIC;    
	\rext/cext2\: INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end hct123;
