-- generated by newgenasym Mon Sep 15 09:26:06 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hct123 is
    port (    
	C:         INOUT  STD_LOGIC;    
	\c/r\:     INOUT  STD_LOGIC;    
	\cl*\:     IN     STD_LOGIC;    
	CLOCK:     IN     STD_LOGIC;    
	\clock*\:  IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC);
end hct123;
