-- generated by newgenasym Sat Feb 28 19:11:40 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pulse_inverter is
    port (    
	PULSE_INV_IN: IN     STD_LOGIC;    
	PULSE_INV_OUT: OUT    STD_LOGIC);
end pulse_inverter;
