-- generated by newgenasym Sun Mar 01 02:51:03 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74f06\ is
    port (    
	D1:        IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	D5:        IN     STD_LOGIC;    
	D6:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\q1*\:     OUT    STD_LOGIC;    
	\q2*\:     OUT    STD_LOGIC;    
	\q3*\:     OUT    STD_LOGIC;    
	\q4*\:     OUT    STD_LOGIC;    
	\q5*\:     OUT    STD_LOGIC;    
	\q6*\:     OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end \74f06\;
