// generated by newgenasym  Thu Apr 23 11:02:22 2015


module ellie_ports (smellie_delay_in, tellie_delay_in);
    output smellie_delay_in;
    output tellie_delay_in;


    initial
        begin
        end

endmodule
