// generated by newgenasym  Fri Mar 06 14:42:26 2015


module ellie_ports (smellie_delay_in, smellie_delay_out, smellie_pulse_out,
        tellie_delay_in, tellie_delay_out, tellie_pulse_out);
    output smellie_delay_in;
    input smellie_delay_out;
    input smellie_pulse_out;
    output tellie_delay_in;
    input tellie_delay_out;
    input tellie_pulse_out;


    initial
        begin
        end

endmodule
