-- generated by newgenasym Thu Apr 23 11:02:22 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ellie_ports is
    port (    
	SMELLIE_DELAY_IN: OUT    STD_LOGIC;    
	TELLIE_DELAY_IN: OUT    STD_LOGIC);
end ellie_ports;
