-- generated by newgenasym Fri Mar 06 14:42:26 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ellie_ports is
    port (    
	SMELLIE_DELAY_IN: OUT    STD_LOGIC;    
	SMELLIE_DELAY_OUT: IN     STD_LOGIC;    
	SMELLIE_PULSE_OUT: IN     STD_LOGIC;    
	TELLIE_DELAY_IN: OUT    STD_LOGIC;    
	TELLIE_DELAY_OUT: IN     STD_LOGIC;    
	TELLIE_PULSE_OUT: IN     STD_LOGIC);
end ellie_ports;
