// generated by newgenasym  Tue Apr 21 13:00:58 2015


module dr610f1_button (a1, a2, b1, b2);
    inout a1;
    inout a2;
    inout b1;
    inout b2;


    initial
        begin
        end

endmodule
