-- generated by newgenasym Tue Apr 21 13:00:58 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dr610f1_button is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC);
end dr610f1_button;
