// generated by newgenasym  Tue Feb 15 11:50:30 2011


module xc2c512 (a1, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9,
        b1, b10, b11, b12, b13, b14, b15, b16, b2, b3, b4, b5, b6, b7, b8,
        b9, c1, c10, c11, c12, c13, c14, c15, c16, c2, c3, c5, c6, c7, c8,
        c9, cdr1, cdr2, d1, d10, d11, d13, d14, d15, d16, d2, d6, d7, d8,
        d9, dge, e1, e10, e11, e12, e13, e14, e15, e16, e2, e4, e6, e7, e8,
        e9, f1, f12, f13, f14, f15, f16, f2, f3, f5, g1, g11, g12, g13, g14,
        g15, g16, g2, g3, g4, g5, gc1, gc2, goe1, goe2, goe3, goe4, gsr1,
        h1, h12, h13, h14, h15, h16, h2, h3, h4, h5, j1, j12, j13, j14, j15,
        j16, j2, j3, j4, j5, k1, k12, k14, k15, k16, k2, k3, k4, k5, l1, l12,
        l13, l14, l15, l16, l2, l3, l4, l5, m1, m10, m11, m12, m13, m14,
        m15, m16, m4, m5, m6, m7, m8, m9, n1, n10, n11, n13, n14, n15, n16,
        n2, n3, n4, n5, n6, n7, n8, n9, p1, p10, p11, p13, p14, p15, p16, p4,
        p6, p7, p8, p9, r1, r10, r12, r13, r14, r15, r16, r2, r3, r4, r5, r6,
        r7, r8, r9, t1, t10, t11, t12, t13, t14, t15, t16, t2, t3, t4, t6,
        t7, t8, t9, tck, tdi, tdo, tms, vaux);
    inout a1;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a16;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout b1;
    inout b10;
    inout b11;
    inout b12;
    inout b13;
    inout b14;
    inout b15;
    inout b16;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout b9;
    inout c1;
    inout c10;
    inout c11;
    inout c12;
    inout c13;
    inout c14;
    inout c15;
    inout c16;
    inout c2;
    inout c3;
    inout c5;
    inout c6;
    inout c7;
    inout c8;
    inout c9;
    inout cdr1;
    inout cdr2;
    inout d1;
    inout d10;
    inout d11;
    inout d13;
    inout d14;
    inout d15;
    inout d16;
    inout d2;
    inout d6;
    inout d7;
    inout d8;
    inout d9;
    inout dge;
    inout e1;
    inout e10;
    inout e11;
    inout e12;
    inout e13;
    inout e14;
    inout e15;
    inout e16;
    inout e2;
    inout e4;
    inout e6;
    inout e7;
    inout e8;
    inout e9;
    inout f1;
    inout f12;
    inout f13;
    inout f14;
    inout f15;
    inout f16;
    inout f2;
    inout f3;
    inout f5;
    inout g1;
    inout g11;
    inout g12;
    inout g13;
    inout g14;
    inout g15;
    inout g16;
    inout g2;
    inout g3;
    inout g4;
    inout g5;
    inout gc1;
    inout gc2;
    inout goe1;
    inout goe2;
    inout goe3;
    inout goe4;
    inout gsr1;
    inout h1;
    inout h12;
    inout h13;
    inout h14;
    inout h15;
    inout h16;
    inout h2;
    inout h3;
    inout h4;
    inout h5;
    inout j1;
    inout j12;
    inout j13;
    inout j14;
    inout j15;
    inout j16;
    inout j2;
    inout j3;
    inout j4;
    inout j5;
    inout k1;
    inout k12;
    inout k14;
    inout k15;
    inout k16;
    inout k2;
    inout k3;
    inout k4;
    inout k5;
    inout l1;
    inout l12;
    inout l13;
    inout l14;
    inout l15;
    inout l16;
    inout l2;
    inout l3;
    inout l4;
    inout l5;
    inout m1;
    inout m10;
    inout m11;
    inout m12;
    inout m13;
    inout m14;
    inout m15;
    inout m16;
    inout m4;
    inout m5;
    inout m6;
    inout m7;
    inout m8;
    inout m9;
    inout n1;
    inout n10;
    inout n11;
    inout n13;
    inout n14;
    inout n15;
    inout n16;
    inout n2;
    inout n3;
    inout n4;
    inout n5;
    inout n6;
    inout n7;
    inout n8;
    inout n9;
    inout p1;
    inout p10;
    inout p11;
    inout p13;
    inout p14;
    inout p15;
    inout p16;
    inout p4;
    inout p6;
    inout p7;
    inout p8;
    inout p9;
    inout r1;
    inout r10;
    inout r12;
    inout r13;
    inout r14;
    inout r15;
    inout r16;
    inout r2;
    inout r3;
    inout r4;
    inout r5;
    inout r6;
    inout r7;
    inout r8;
    inout r9;
    inout t1;
    inout t10;
    inout t11;
    inout t12;
    inout t13;
    inout t14;
    inout t15;
    inout t16;
    inout t2;
    inout t3;
    inout t4;
    inout t6;
    inout t7;
    inout t8;
    inout t9;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    input vaux;


    initial
        begin
        end

endmodule
