-- generated by newgenasym Mon Jul 14 18:25:29 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity f08 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	O:         OUT    STD_LOGIC);
end f08;
