// generated by newgenasym  Fri Mar 06 14:18:44 2015


module mtca_mimic_ports (mtca_mimic1_out_n, mtca_mimic1_out_p,
        mtca_mimic1_pulse_anal, mtca_mimic2_out_n,
        mtca_mimic2_out_p, mtca_mimic2_pulse_anal);
    input mtca_mimic1_out_n;
    input mtca_mimic1_out_p;
    output mtca_mimic1_pulse_anal;
    input mtca_mimic2_out_n;
    input mtca_mimic2_out_p;
    output mtca_mimic2_pulse_anal;


    initial
        begin
        end

endmodule
