// generated by newgenasym  Thu Apr 23 10:23:16 2015


module mtca_mimic_ports (mtca_mimic1_out_n, mtca_mimic1_out_p,
        mtca_mimic2_out_n, mtca_mimic2_out_p,
        mtca_mimic2_pulse_anal);
    input mtca_mimic1_out_n;
    input mtca_mimic1_out_p;
    input mtca_mimic2_out_n;
    input mtca_mimic2_out_p;
    output mtca_mimic2_pulse_anal;


    initial
        begin
        end

endmodule
