-- generated by newgenasym Thu Apr 23 10:23:16 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mtca_mimic_ports is
    port (    
	MTCA_MIMIC1_OUT_N: IN     STD_LOGIC;    
	MTCA_MIMIC1_OUT_P: IN     STD_LOGIC;    
	MTCA_MIMIC2_OUT_N: IN     STD_LOGIC;    
	MTCA_MIMIC2_OUT_P: IN     STD_LOGIC;    
	MTCA_MIMIC2_PULSE_ANAL: OUT    STD_LOGIC);
end mtca_mimic_ports;
