// generated by newgenasym  Wed Mar 04 18:38:30 2015


module translation (ecl_to_lvds_out_n, ecl_to_lvds_out_p, ecl_to_nim_in,
        ecl_to_nim_out, ecl_to_ttl_out, lvds_to_ecl_in,
        lvds_to_ecl_out_n, lvds_to_ecl_out_p, nim_to_ecl_in,
        ttl_to_ecl_in, ttl_to_ecl_out_n, ttl_to_ecl_out_p);
    output ecl_to_lvds_out_n;
    output ecl_to_lvds_out_p;
    input ecl_to_nim_in;
    output ecl_to_nim_out;
    output ecl_to_ttl_out;
    input lvds_to_ecl_in;
    output lvds_to_ecl_out_n;
    output lvds_to_ecl_out_p;
    input nim_to_ecl_in;
    input ttl_to_ecl_in;
    output ttl_to_ecl_out_n;
    output ttl_to_ecl_out_p;


    initial
        begin
        end

endmodule
