-- generated by newgenasym Wed Mar 04 18:38:30 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity translation is
    port (    
	ECL_TO_LVDS_OUT_N: OUT    STD_LOGIC;    
	ECL_TO_LVDS_OUT_P: OUT    STD_LOGIC;    
	ECL_TO_NIM_IN: IN     STD_LOGIC;    
	ECL_TO_NIM_OUT: OUT    STD_LOGIC;    
	ECL_TO_TTL_OUT: OUT    STD_LOGIC;    
	LVDS_TO_ECL_IN: IN     STD_LOGIC;    
	LVDS_TO_ECL_OUT_N: OUT    STD_LOGIC;    
	LVDS_TO_ECL_OUT_P: OUT    STD_LOGIC;    
	NIM_TO_ECL_IN: IN     STD_LOGIC;    
	TTL_TO_ECL_IN: IN     STD_LOGIC;    
	TTL_TO_ECL_OUT_N: OUT    STD_LOGIC;    
	TTL_TO_ECL_OUT_P: OUT    STD_LOGIC);
end translation;
