// generated by newgenasym  Tue Oct  5 17:03:05 2010


module lt1055 (bal1, bal2, \in+ , \in- , out, \vcc+ , \vcc- );
    inout bal1;
    inout bal2;
    inout \in+ ;
    inout \in- ;
    inout out;
    input \vcc+ ;
    input \vcc- ;


    initial
        begin
        end

endmodule
