-- generated by newgenasym Tue Oct  5 17:03:05 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LT1055 is
    port (    
	BAL1:      INOUT  STD_LOGIC;    
	BAL2:      INOUT  STD_LOGIC;    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\vcc+\:    IN     STD_LOGIC;    
	\vcc-\:    IN     STD_LOGIC);
end LT1055;
