-- generated by newgenasym Thu Apr 07 16:31:04 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsmd0805size is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end rsmd0805size;
