// generated by newgenasym  Mon Aug  2 09:59:21 2010


module dipswitch (a0, a1, a2, a3, a4, a5, a6, a7, b0, b1, b2, b3, b4, b5, b6, b7);
    input a0;
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    output b0;
    output b1;
    output b2;
    output b3;
    output b4;
    output b5;
    output b6;
    output b7;


    initial
        begin
        end

endmodule
