-- generated by newgenasym Mon Aug  2 09:59:21 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dipswitch is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	A6:        IN     STD_LOGIC;    
	A7:        IN     STD_LOGIC;    
	B0:        OUT    STD_LOGIC;    
	B1:        OUT    STD_LOGIC;    
	B2:        OUT    STD_LOGIC;    
	B3:        OUT    STD_LOGIC;    
	B4:        OUT    STD_LOGIC;    
	B5:        OUT    STD_LOGIC;    
	B6:        OUT    STD_LOGIC;    
	B7:        OUT    STD_LOGIC);
end dipswitch;
