// generated by newgenasym  Fri Mar 06 19:00:05 2015


module caen_analog_ports (caen_out_anal, pulse_in_anal, scope_out_anal);
    input [0:7] caen_out_anal;
    output [0:11] pulse_in_anal;
    input [0:7] scope_out_anal;


    initial
        begin
        end

endmodule
