-- generated by newgenasym Fri Mar 06 19:00:05 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_analog_ports is
    port (    
	CAEN_OUT_ANAL: IN     STD_LOGIC_VECTOR (0 TO 7);    
	PULSE_IN_ANAL: OUT    STD_LOGIC_VECTOR (0 TO 11);    
	SCOPE_OUT_ANAL: IN     STD_LOGIC_VECTOR (0 TO 7));
end caen_analog_ports;
