-- generated by newgenasym Mon Sep 13 13:50:27 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_1206 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end led_1206;
