-- generated by newgenasym Thu May 20 11:02:16 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsmd0805_1pct is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end rsmd0805_1pct;
