// generated by newgenasym  Fri Aug 22 11:48:37 2014


module hct238 (a0, a1, a2, e1, e2, e3, y0, y1, y2, y3, y4, y5, y6, y7);
    input a0;
    input a1;
    input a2;
    output e1;
    output e2;
    output e3;
    output y0;
    output y1;
    output y2;
    output y3;
    output y4;
    output y5;
    output y6;
    output y7;


    initial
        begin
        end

endmodule
