-- generated by newgenasym Fri Aug 22 11:48:37 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hct238 is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	E1:        OUT    STD_LOGIC;    
	E2:        OUT    STD_LOGIC;    
	E3:        OUT    STD_LOGIC;    
	Y0:        OUT    STD_LOGIC;    
	Y1:        OUT    STD_LOGIC;    
	Y2:        OUT    STD_LOGIC;    
	Y3:        OUT    STD_LOGIC;    
	Y4:        OUT    STD_LOGIC;    
	Y5:        OUT    STD_LOGIC;    
	Y6:        OUT    STD_LOGIC;    
	Y7:        OUT    STD_LOGIC);
end hct238;
