// generated by newgenasym  Thu May 28 14:14:55 2015


module max17501 (\1 , \10 , \11 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;


    initial
        begin
        end

endmodule
