-- generated by newgenasym Thu May 28 14:14:55 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max17501 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\10\:      INOUT  STD_LOGIC;    
	\11\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC);
end max17501;
