// generated by newgenasym  Thu May 28 12:21:41 2015


module lm2596 (fb, gnd, \on* , tab, vin, vout);
    inout fb;
    input gnd;
    input \on* ;
    inout tab;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
