-- generated by newgenasym Thu May 28 12:21:41 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm2596 is
    port (    
	FB:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\on*\:     IN     STD_LOGIC;    
	TAB:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end lm2596;
