// generated by newgenasym  Wed Oct 22 13:32:12 2014


module ad96685 (grnd1, grnd2, inn, inp, ltch, qn, qp, vn, vp);
    input grnd1;
    input grnd2;
    input inn;
    input inp;
    output ltch;
    output qn;
    output qp;
    input vn;
    input vp;


    initial
        begin
        end

endmodule
