-- generated by newgenasym Wed Oct 22 13:32:12 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad96685 is
    port (    
	GRND1:     IN     STD_LOGIC;    
	GRND2:     IN     STD_LOGIC;    
	INN:       IN     STD_LOGIC;    
	INP:       IN     STD_LOGIC;    
	LTCH:      OUT    STD_LOGIC;    
	QN:        OUT    STD_LOGIC;    
	QP:        OUT    STD_LOGIC;    
	VN:        IN     STD_LOGIC;    
	VP:        IN     STD_LOGIC);
end ad96685;
