-- generated by newgenasym Sat Mar 07 15:44:29 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity scaler_ports is
    port (    
	SCALER:    IN     STD_LOGIC_VECTOR (1 TO 6));
end scaler_ports;
