-- generated by newgenasym Mon Sep 13 13:45:22 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity csmd1206 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         OUT    STD_LOGIC);
end csmd1206;
