// generated by newgenasym  Mon Jul 11 17:48:15 2011


module ad7249 (bbarc, \clr* , \ldac* , refin, refout, rofs, sclk, sdin, \sync* ,
        vout);
    input bbarc;
    input \clr* ;
    input \ldac* ;
    input refin;
    output refout;
    output rofs;
    input sclk;
    input sdin;
    input \sync* ;
    output vout;


    initial
        begin
        end

endmodule
