-- generated by newgenasym Mon Jul 11 17:48:15 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad7249 is
    port (    
	BBARC:     IN     STD_LOGIC;    
	\clr*\:    IN     STD_LOGIC;    
	\ldac*\:   IN     STD_LOGIC;    
	REFIN:     IN     STD_LOGIC;    
	REFOUT:    OUT    STD_LOGIC;    
	ROFS:      OUT    STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	SDIN:      IN     STD_LOGIC;    
	\sync*\:   IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC);
end ad7249;
