// generated by newgenasym  Wed Oct 22 10:44:40 2014


module ref02 (gnd, temp, trim, vin, vout);
    input gnd;
    inout temp;
    inout trim;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
