// generated by newgenasym  Fri Mar 06 19:00:02 2015


module caen_digital_ports (gt_nim, sync24_lvds_n, sync24_lvds_p, sync_lvds_n,
        sync_lvds_p);
    input gt_nim;
    input sync24_lvds_n;
    input sync24_lvds_p;
    input sync_lvds_n;
    input sync_lvds_p;


    initial
        begin
        end

endmodule
