-- generated by newgenasym Fri Mar 06 19:00:02 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_digital_ports is
    port (    
	GT_NIM:    IN     STD_LOGIC;    
	SYNC24_LVDS_N: IN     STD_LOGIC;    
	SYNC24_LVDS_P: IN     STD_LOGIC;    
	SYNC_LVDS_N: IN     STD_LOGIC;    
	SYNC_LVDS_P: IN     STD_LOGIC);
end caen_digital_ports;
