// generated by newgenasym  Tue Mar 03 16:54:16 2015


module ostoq047150 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
