-- generated by newgenasym Tue Mar 03 16:54:16 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ostoq047150 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end ostoq047150;
