// generated by newgenasym  Sun Mar 01 21:37:54 2015


module sy100el05 (d_a, \d_a* , d_b, \d_b* , gnd, q, \q* , vee);
    input d_a;
    input \d_a* ;
    input d_b;
    input \d_b* ;
    input gnd;
    output q;
    output \q* ;
    input vee;


    initial
        begin
        end

endmodule
