-- generated by newgenasym Sun Mar 01 21:37:54 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sy100el05 is
    port (    
	D_A:       IN     STD_LOGIC;    
	\d_a*\:    IN     STD_LOGIC;    
	D_B:       IN     STD_LOGIC;    
	\d_b*\:    IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end sy100el05;
