// generated by newgenasym  Mon Nov 17 13:22:28 2008


module \10104  (d0, d1, d2, d3, d4, d5, d6, d7, q0, q1, q2, q3, \|q|3* );
    input d0;
    input d1;
    input d2;
    input d3;
    input d4;
    input d5;
    input d6;
    input d7;
    output q0;
    output q1;
    output q2;
    output q3;
    output \|q|3* ;


    initial
        begin
        end

endmodule
