// generated by newgenasym  Sun Mar 01 02:08:03 2015


module mtca_mimic (clk, data, data_rdy, dgt, gt, le, \lo* , pulse1_anal,
        pulse2_anal, trig1_out_n, trig1_out_p, trig2_out_n,
        trig2_out_p);
    input clk;
    input data;
    input data_rdy;
    input dgt;
    input gt;
    input le;
    input \lo* ;
    input pulse1_anal;
    input pulse2_anal;
    output trig1_out_n;
    output trig1_out_p;
    output trig2_out_n;
    output trig2_out_p;


    initial
        begin
        end

endmodule
