-- generated by newgenasym Thu Apr 16 14:43:12 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mtca_mimic is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	DGT:       IN     STD_LOGIC;    
	GT:        IN     STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	\lo*\:     IN     STD_LOGIC;    
	PULSE1_ANAL: IN     STD_LOGIC;    
	PULSE2_ANAL: IN     STD_LOGIC;    
	TRIG1_OUT_N: OUT    STD_LOGIC;    
	TRIG1_OUT_P: OUT    STD_LOGIC;    
	TRIG1_OUT_TTL: OUT    STD_LOGIC;    
	TRIG2_OUT_N: OUT    STD_LOGIC;    
	TRIG2_OUT_P: OUT    STD_LOGIC;    
	TRIG2_OUT_TTL: OUT    STD_LOGIC);
end mtca_mimic;
