// generated by newgenasym  Sat Feb 28 18:41:09 2015


module mc10h124 (a_in, a_out, \a_out* , b_in, b_out, \b_out* , c_in, c_out,
        \c_out* , common, d_in, d_out, \d_out* , gnd, vcc, vee);
    input a_in;
    output a_out;
    output \a_out* ;
    input b_in;
    output b_out;
    output \b_out* ;
    input c_in;
    output c_out;
    output \c_out* ;
    input common;
    input d_in;
    output d_out;
    output \d_out* ;
    input gnd;
    input vcc;
    input vee;


    initial
        begin
        end

endmodule
