// generated by newgenasym  Thu Oct 30 10:38:36 2014


module mc10h124 (common, in, out, \out* );
    input common;
    input in;
    output out;
    output \out* ;


    initial
        begin
        end

endmodule
