-- generated by newgenasym Sat Feb 28 18:41:09 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc10h124 is
    port (    
	A_IN:      IN     STD_LOGIC;    
	A_OUT:     OUT    STD_LOGIC;    
	\a_out*\:  OUT    STD_LOGIC;    
	B_IN:      IN     STD_LOGIC;    
	B_OUT:     OUT    STD_LOGIC;    
	\b_out*\:  OUT    STD_LOGIC;    
	C_IN:      IN     STD_LOGIC;    
	C_OUT:     OUT    STD_LOGIC;    
	\c_out*\:  OUT    STD_LOGIC;    
	COMMON:    IN     STD_LOGIC;    
	D_IN:      IN     STD_LOGIC;    
	D_OUT:     OUT    STD_LOGIC;    
	\d_out*\:  OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end mc10h124;
