-- generated by newgenasym Thu Oct 30 10:38:36 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc10h124 is
    port (    
	COMMON:    IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	\out*\:    OUT    STD_LOGIC);
end mc10h124;
