// generated by newgenasym  Sat Feb 28 21:06:58 2015


module generic_delays (clk, data, delay_in, delay_out, le, pulse_in, pulse_out);
    input clk;
    input data;
    input delay_in;
    output delay_out;
    input le;
    input pulse_in;
    output pulse_out;


    initial
        begin
        end

endmodule
