-- generated by newgenasym Sat Feb 28 21:06:58 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity generic_delays is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DELAY_IN:  IN     STD_LOGIC;    
	DELAY_OUT: OUT    STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	PULSE_IN:  IN     STD_LOGIC;    
	PULSE_OUT: OUT    STD_LOGIC);
end generic_delays;
