// generated by newgenasym  Mon Jul 11 17:44:30 2011


module ad96687 (in, \in* , ltchen, \ltchen* , q, \q* );
    input in;
    input \in* ;
    input ltchen;
    input \ltchen* ;
    output q;
    output \q* ;


    initial
        begin
        end

endmodule
