// generated by newgenasym  Sat Feb 28 21:51:39 2015


module ad96687 (gnd1, gnd2, in_n1, in_n2, in_p1, in_p2, le1, \le1* , le2, \le2* ,
        q1, \q1* , q2, \q2* , \vs+ , \vs- );
    input gnd1;
    input gnd2;
    inout in_n1;
    inout in_n2;
    inout in_p1;
    inout in_p2;
    input le1;
    input \le1* ;
    input le2;
    input \le2* ;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    input \vs+ ;
    input \vs- ;


    initial
        begin
        end

endmodule
