-- generated by newgenasym Mon Jul 11 17:44:30 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad96687 is
    port (    
	\in\:      IN     STD_LOGIC;    
	\in*\:     IN     STD_LOGIC;    
	LTCHEN:    IN     STD_LOGIC;    
	\ltchen*\: IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC);
end ad96687;
