-- generated by newgenasym Sat Feb 28 21:51:39 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad96687 is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	IN_N1:     INOUT  STD_LOGIC;    
	IN_N2:     INOUT  STD_LOGIC;    
	IN_P1:     INOUT  STD_LOGIC;    
	IN_P2:     INOUT  STD_LOGIC;    
	LE1:       IN     STD_LOGIC;    
	\le1*\:    IN     STD_LOGIC;    
	LE2:       IN     STD_LOGIC;    
	\le2*\:    IN     STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	\q1*\:     OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	\q2*\:     OUT    STD_LOGIC;    
	\vs+\:     IN     STD_LOGIC;    
	\vs-\:     IN     STD_LOGIC);
end ad96687;
