-- generated by newgenasym Wed Nov  3 16:26:47 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity csmd0603 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end csmd0603;
