// generated by newgenasym  Mon Jun 01 12:06:56 2015


module ds102350 (\clk/p1 , \d/p2 , gnd, in, \le* , ms, out, p3, p4, p5, p6, p7, ps, pwm,
        \q/p0 , vcc);
    input \clk/p1 ;
    input \d/p2 ;
    input gnd;
    input in;
    input \le* ;
    input ms;
    output out;
    input p3;
    input p4;
    input p5;
    input p6;
    input p7;
    input ps;
    output pwm;
    input \q/p0 ;
    input vcc;


    initial
        begin
        end

endmodule
