-- generated by newgenasym Thu May 28 14:27:53 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity srr6038 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end srr6038;
