-- generated by newgenasym Tue May 18 12:05:02 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MMBTH81LT1 is
    port (    
	B:         IN     STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end MMBTH81LT1;
