-- generated by newgenasym Wed Oct 22 13:49:37 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa4277 is
    port (    
	\+in_a\:   INOUT  STD_LOGIC;    
	\+in_b\:   INOUT  STD_LOGIC;    
	\+in_c\:   INOUT  STD_LOGIC;    
	\+in_d\:   INOUT  STD_LOGIC;    
	\-in_a\:   INOUT  STD_LOGIC;    
	\-in_b\:   INOUT  STD_LOGIC;    
	\-in_c\:   INOUT  STD_LOGIC;    
	\-in_d\:   INOUT  STD_LOGIC;    
	OUT_A:     INOUT  STD_LOGIC;    
	OUT_B:     INOUT  STD_LOGIC;    
	OUT_C:     INOUT  STD_LOGIC;    
	OUT_D:     INOUT  STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end opa4277;
