// generated by newgenasym  Fri Jul 01 17:52:50 2011


module ds102350 (in, \le* , ms, out, p, ps, pwm);
    input in;
    input \le* ;
    input ms;
    output out;
    input [7:0] p;
    input ps;
    output pwm;


    initial
        begin
        end

endmodule
