// generated by newgenasym  Mon Jun 01 12:07:39 2015


module ds102350bkup (in, \le* , ms, out, p, ps, pwm);
    input in;
    input \le* ;
    input ms;
    output out;
    input [7:0] p;
    input ps;
    output pwm;


    initial
        begin
        end

endmodule
