-- generated by newgenasym Fri Jul 01 17:52:50 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DS102350 is
    port (    
	\in\:      IN     STD_LOGIC;    
	\le*\:     IN     STD_LOGIC;    
	MS:        IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	P:         IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	PS:        IN     STD_LOGIC;    
	PWM:       OUT    STD_LOGIC);
end DS102350;
