-- generated by newgenasym Mon Jun 01 12:07:39 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds102350bkup is
    port (    
	\in\:      IN     STD_LOGIC;    
	\le*\:     IN     STD_LOGIC;    
	MS:        IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	P:         IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	PS:        IN     STD_LOGIC;    
	PWM:       OUT    STD_LOGIC);
end ds102350bkup;
