-- generated by newgenasym Tue Jan 27 14:33:46 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity conn30 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\11\:      IN     STD_LOGIC;    
	\12\:      IN     STD_LOGIC;    
	\13\:      IN     STD_LOGIC;    
	\14\:      IN     STD_LOGIC;    
	\15\:      IN     STD_LOGIC;    
	\16\:      IN     STD_LOGIC;    
	\17\:      IN     STD_LOGIC;    
	\18\:      IN     STD_LOGIC;    
	\19\:      IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\20\:      IN     STD_LOGIC;    
	\21\:      IN     STD_LOGIC;    
	\22\:      IN     STD_LOGIC;    
	\23\:      IN     STD_LOGIC;    
	\24\:      IN     STD_LOGIC;    
	\25\:      IN     STD_LOGIC;    
	\26\:      IN     STD_LOGIC;    
	\27\:      IN     STD_LOGIC;    
	\28\:      IN     STD_LOGIC;    
	\29\:      IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\30\:      IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC;    
	\9\:       IN     STD_LOGIC);
end conn30;
