// generated by newgenasym  Fri Jul 30 18:03:39 2010


module \74f245  (a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8, dir,
        \oe* );
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    output b1;
    output b2;
    output b3;
    output b4;
    output b5;
    output b6;
    output b7;
    output b8;
    input dir;
    input \oe* ;


    initial
        begin
        end

endmodule
