-- generated by newgenasym Fri Mar 06 18:55:27 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_ports is
    port (    
	CAEN_OUT_ANAL: IN     STD_LOGIC_VECTOR (0 TO 7);    
	GT_NIM:    IN     STD_LOGIC;    
	PULSE_IN_ANAL: OUT    STD_LOGIC_VECTOR (0 TO 11);    
	SCOPE_OUT_ANAL: IN     STD_LOGIC_VECTOR (0 TO 7);    
	SYNC24_LVDS_N: IN     STD_LOGIC;    
	SYNC24_LVDS_P: IN     STD_LOGIC;    
	SYNC_LVDS_N: IN     STD_LOGIC;    
	SYNC_LVDS_P: IN     STD_LOGIC);
end caen_ports;
