// generated by newgenasym  Sat Feb 28 18:17:35 2015


module mc10e116 (d0, \d0* , d1, \d1* , d2, \d2* , d3, \d3* , d4, \d4* , gnd0, gnd1, gnd2,
        gnd3, gnd4, gnd5, q0, \q0* , q1, \q1* , q2, \q2* , q3, \q3* , q4, \q4* , vbb,
        vee);
    input d0;
    input \d0* ;
    input d1;
    input \d1* ;
    input d2;
    input \d2* ;
    input d3;
    input \d3* ;
    input d4;
    input \d4* ;
    input gnd0;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    output q0;
    output \q0* ;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    output q3;
    output \q3* ;
    output q4;
    output \q4* ;
    output vbb;
    input vee;


    initial
        begin
        end

endmodule
