-- generated by newgenasym Thu Feb 18 15:42:31 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hv_cer_cap is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end hv_cer_cap;
