// generated by newgenasym  Tue Aug 18 11:23:27 2009


module tlc274_new (nin, nvss, out, pin, pvss);
    input nin;
    inout nvss;
    output out;
    input pin;
    inout pvss;


    initial
        begin
        end

endmodule
