-- generated by newgenasym Tue Aug 18 11:23:27 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TLC274_NEW is
    port (    
	NIN:       IN     STD_LOGIC;    
	NVSS:      INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	PIN:       IN     STD_LOGIC;    
	PVSS:      INOUT  STD_LOGIC);
end TLC274_NEW;
