// generated by newgenasym  Mon Sep 08 19:03:45 2014


module ad7243 (agnd, bncp, \clr* , cs, d, dcen, dgnd, \ecl#20com , \ecl#20ref , \ldac* ,
        le, \off#20adj , q, \q* , \qr* , refin, refout, reset, \reset* , rofs, rs,
        sclk, sdin, sdo, \sync* , trig, \trig* , vdd, vout, vss);
    input agnd;
    input bncp;
    input \clr* ;
    inout cs;
    input [7:0] d;
    input dcen;
    input dgnd;
    inout \ecl#20com ;
    inout \ecl#20ref ;
    input \ldac* ;
    input le;
    input \off#20adj ;
    output q;
    output \q* ;
    output \qr* ;
    input refin;
    output refout;
    input reset;
    input \reset* ;
    input rofs;
    inout rs;
    input sclk;
    input sdin;
    output sdo;
    input \sync* ;
    input trig;
    input \trig* ;
    input vdd;
    output vout;
    input vss;


    initial
        begin
        end

endmodule
