// generated by newgenasym  Tue May 18 12:05:27 2010


module \10e116  (a, \b* , ref, y, \y* );
    parameter    section = 2;
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] \b* ;
    output ref;
    output [size-1:0] y;
    output [size-1:0] \y* ;


    initial
        begin
        end

endmodule
