-- generated by newgenasym Tue May 18 12:05:27 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10e116\ is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\b*\:      IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	REF:       OUT    STD_LOGIC;    
	Y:         OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y*\:      OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \10e116\;
