// generated by newgenasym  Mon Aug 16 14:00:05 2010


module ths3001 (\in+ , \in- , out, \vcc+ , \vcc- );
    inout \in+ ;
    inout \in- ;
    inout out;
    input \vcc+ ;
    input \vcc- ;


    initial
        begin
        end

endmodule
