-- generated by newgenasym Mon Aug 16 14:00:05 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity THS3001 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\vcc+\:    IN     STD_LOGIC;    
	\vcc-\:    IN     STD_LOGIC);
end THS3001;
