// generated by chdl_uprev Fri Sep 12 01:57:34 1997

// Modified to support swift models
`timescale 1ns/100ps

module hct123 (c, \c/r , \cl* , clock, \clock* , q, \q* );
    parameter    ModelType = "SWIFT";
    parameter    TimingVersion = "74HCT123";
    /*
Legal values of TimingVersion parameter are: 
CD74HCT123
*/ 
    parameter    DelayRange = "max";
    parameter    MemoryFile = "memory";
    input clock;
    input \clock* ;
    input \cl* ;
    output q;
    output \q* ;
    inout \c/r ;
    inout c;


    ttl123 #(ModelType, TimingVersion, DelayRange, MemoryFile)  inst1 (.A(\clock* ),
                               .B(clock),
                               .C(c),
                               .CLR(\cl* ),
                               .Q(q),
                               .QN(\q* ),
                               .RC(\c/r ) );
endmodule
