-- generated by newgenasym Wed Mar 04 19:06:10 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity trnslation is
    port (    
	ECL_TO_LVDS_OUT_N: OUT    STD_LOGIC;    
	ECL_TO_LVDS_OUT_P: OUT    STD_LOGIC;    
	ECL_TO_NIM_OUT: OUT    STD_LOGIC;    
	ECL_TO_TTL_OUT: OUT    STD_LOGIC;    
	LVDS_TO_ECL_OUT_N: OUT    STD_LOGIC;    
	LVDS_TO_ECL_OUT_P: OUT    STD_LOGIC;    
	TTL_TO_ECL_OUT_N: OUT    STD_LOGIC;    
	TTL_TO_ECL_OUT_P: OUT    STD_LOGIC);
end trnslation;
