// generated by newgenasym  Fri May 29 16:48:49 2015


module lm2595 (fb, gnd, \on* , tab, vin, vout);
    inout fb;
    inout gnd;
    inout \on* ;
    inout tab;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
