-- generated by newgenasym Fri May 29 16:48:49 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm2595 is
    port (    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\on*\:     INOUT  STD_LOGIC;    
	TAB:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end lm2595;
