// generated by newgenasym  Wed Aug 20 15:56:21 2014


module \74hct04  (a0, a1, a2, a3, a4, a5, \y0* , \y1* , \y2* , \y3* , \y4* , \y5* );
    input a0;
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    output \y0* ;
    output \y1* ;
    output \y2* ;
    output \y3* ;
    output \y4* ;
    output \y5* ;


    initial
        begin
        end

endmodule
