-- generated by newgenasym Mon Sep 13 13:50:11 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_small is
    port (    
	AN:        INOUT  STD_LOGIC;    
	CAT:       INOUT  STD_LOGIC);
end led_small;
