// generated by newgenasym  Thu Oct 16 16:05:56 2014


module max9375 (in, \in* , out, \out* );
    input in;
    input \in* ;
    output out;
    output \out* ;


    initial
        begin
        end

endmodule
