-- generated by newgenasym Thu Oct 16 16:05:56 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max9375 is
    port (    
	\in\:      IN     STD_LOGIC;    
	\in*\:     IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	\out*\:    OUT    STD_LOGIC);
end max9375;
