-- generated by newgenasym Thu May 28 15:34:40 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lv06a\ is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	A6:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y1:        OUT    STD_LOGIC;    
	Y2:        OUT    STD_LOGIC;    
	Y3:        OUT    STD_LOGIC;    
	Y4:        OUT    STD_LOGIC;    
	Y5:        OUT    STD_LOGIC;    
	Y6:        OUT    STD_LOGIC);
end \74lv06a\;
