// generated by newgenasym  Sat Mar 07 18:48:54 2015


module default_clk_sel (bckp_clk, clk_sel, default_clk, reset, reset_ecl_p,
        tub_clk_in);
    output bckp_clk;
    input clk_sel;
    output default_clk;
    input reset;
    output reset_ecl_p;
    input tub_clk_in;


    initial
        begin
        end

endmodule
