// generated by newgenasym  Fri May 15 14:42:14 2015


module default_clk_sel (bckp_clk, clk_sel, default_clk, reset, reset_ecl_p,
        tub_clk_in_n, tub_clk_in_p);
    output bckp_clk;
    input clk_sel;
    output default_clk;
    input reset;
    output reset_ecl_p;
    input tub_clk_in_n;
    input tub_clk_in_p;


    initial
        begin
        end

endmodule
