// generated by newgenasym  Sun Mar 01 15:24:23 2015


module default_clk_sel (bckp_clk, clk_sel, default_clk, reset, tub_clk_in);
    output bckp_clk;
    input clk_sel;
    output default_clk;
    input reset;
    input tub_clk_in;


    initial
        begin
        end

endmodule
