-- generated by newgenasym Fri May 15 14:42:14 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity default_clk_sel is
    port (    
	BCKP_CLK:  OUT    STD_LOGIC;    
	CLK_SEL:   IN     STD_LOGIC;    
	DEFAULT_CLK: OUT    STD_LOGIC;    
	RESET:     IN     STD_LOGIC;    
	RESET_ECL_P: OUT    STD_LOGIC;    
	TUB_CLK_IN_N: IN     STD_LOGIC;    
	TUB_CLK_IN_P: IN     STD_LOGIC);
end default_clk_sel;
