-- generated by newgenasym Thu May 28 17:05:00 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MC7805K_L is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC;    
	REF:       INOUT  STD_LOGIC);
end MC7805K_L;
