// generated by newgenasym  Sat Feb 28 21:29:50 2015


module general_utilities (clk, data, generic_delay_in, generic_delay_out,
        generic_pulse_in, generic_pulse_out, le, pulse_inv_in,
        pulse_inv_out, ribbon_pulse_in_n, ribbon_pulse_in_p,
        ribbon_pulse_out_n, ribbon_pulse_out_p);
    input clk;
    input data;
    input generic_delay_in;
    output generic_delay_out;
    input generic_pulse_in;
    output generic_pulse_out;
    input le;
    input pulse_inv_in;
    output pulse_inv_out;
    input ribbon_pulse_in_n;
    input ribbon_pulse_in_p;
    output ribbon_pulse_out_n;
    output ribbon_pulse_out_p;


    initial
        begin
        end

endmodule
