// generated by newgenasym  Thu Mar 05 13:07:25 2015


module general_utilities (clk, data, ecl_to_lvds_in, ecl_to_lvds_out_n,
        ecl_to_lvds_out_p, ecl_to_nim_in, ecl_to_nim_out,
        ecl_to_ttl_in, ecl_to_ttl_out, generic_delay_in,
        generic_delay_out, generic_pulse_in, generic_pulse_out,
        le, lvds_to_ecl_in_n, lvds_to_ecl_in_p, lvds_to_ecl_out,
        nim_to_ecl_in, nim_to_ecl_out, pulse_inv_in,
        pulse_inv_out, ribbon_pulse_in_n, ribbon_pulse_in_p,
        ribbon_pulse_out_n, ribbon_pulse_out_p, ttl_to_ecl_in,
        ttl_to_ecl_out);
    input clk;
    input data;
    input ecl_to_lvds_in;
    output ecl_to_lvds_out_n;
    output ecl_to_lvds_out_p;
    input ecl_to_nim_in;
    output ecl_to_nim_out;
    input ecl_to_ttl_in;
    output ecl_to_ttl_out;
    input generic_delay_in;
    output generic_delay_out;
    input generic_pulse_in;
    output generic_pulse_out;
    input le;
    input lvds_to_ecl_in_n;
    input lvds_to_ecl_in_p;
    output lvds_to_ecl_out;
    input nim_to_ecl_in;
    output nim_to_ecl_out;
    input pulse_inv_in;
    output pulse_inv_out;
    input ribbon_pulse_in_n;
    input ribbon_pulse_in_p;
    output ribbon_pulse_out_n;
    output ribbon_pulse_out_p;
    input ttl_to_ecl_in;
    output ttl_to_ecl_out;


    initial
        begin
        end

endmodule
