-- generated by newgenasym Thu Mar 05 13:07:25 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity general_utilities is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	ECL_TO_LVDS_IN: IN     STD_LOGIC;    
	ECL_TO_LVDS_OUT_N: OUT    STD_LOGIC;    
	ECL_TO_LVDS_OUT_P: OUT    STD_LOGIC;    
	ECL_TO_NIM_IN: IN     STD_LOGIC;    
	ECL_TO_NIM_OUT: OUT    STD_LOGIC;    
	ECL_TO_TTL_IN: IN     STD_LOGIC;    
	ECL_TO_TTL_OUT: OUT    STD_LOGIC;    
	GENERIC_DELAY_IN: IN     STD_LOGIC;    
	GENERIC_DELAY_OUT: OUT    STD_LOGIC;    
	GENERIC_PULSE_IN: IN     STD_LOGIC;    
	GENERIC_PULSE_OUT: OUT    STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	LVDS_TO_ECL_IN_N: IN     STD_LOGIC;    
	LVDS_TO_ECL_IN_P: IN     STD_LOGIC;    
	LVDS_TO_ECL_OUT: OUT    STD_LOGIC;    
	NIM_TO_ECL_IN: IN     STD_LOGIC;    
	NIM_TO_ECL_OUT: OUT    STD_LOGIC;    
	PULSE_INV_IN: IN     STD_LOGIC;    
	PULSE_INV_OUT: OUT    STD_LOGIC;    
	RIBBON_PULSE_IN_N: IN     STD_LOGIC;    
	RIBBON_PULSE_IN_P: IN     STD_LOGIC;    
	RIBBON_PULSE_OUT_N: OUT    STD_LOGIC;    
	RIBBON_PULSE_OUT_P: OUT    STD_LOGIC;    
	TTL_TO_ECL_IN: IN     STD_LOGIC;    
	TTL_TO_ECL_OUT: OUT    STD_LOGIC);
end general_utilities;
