-- generated by newgenasym Sat Feb 28 21:29:50 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity general_utilities is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	GENERIC_DELAY_IN: IN     STD_LOGIC;    
	GENERIC_DELAY_OUT: OUT    STD_LOGIC;    
	GENERIC_PULSE_IN: IN     STD_LOGIC;    
	GENERIC_PULSE_OUT: OUT    STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	PULSE_INV_IN: IN     STD_LOGIC;    
	PULSE_INV_OUT: OUT    STD_LOGIC;    
	RIBBON_PULSE_IN_N: IN     STD_LOGIC;    
	RIBBON_PULSE_IN_P: IN     STD_LOGIC;    
	RIBBON_PULSE_OUT_N: OUT    STD_LOGIC;    
	RIBBON_PULSE_OUT_P: OUT    STD_LOGIC);
end general_utilities;
