// generated by newgenasym  Thu Mar 05 15:15:57 2015


module lo_gen (clk, data, dgt2, dgt_n, dgt_p, gt_ttl, le, lo_sel, lo_star2,
        lo_star_out_n, lo_star_out_p, \mtcd_lo* );
    input clk;
    input data;
    output dgt2;
    output dgt_n;
    output dgt_p;
    input gt_ttl;
    input le;
    input lo_sel;
    output lo_star2;
    output lo_star_out_n;
    output lo_star_out_p;
    input \mtcd_lo* ;


    initial
        begin
        end

endmodule
