// generated by newgenasym  Sat Feb 28 18:14:07 2015


module lo_gen (clk, data, dgt_n, dgt_p, gt_ttl, le, lo, \lo* , lo_sel,
        \mtcd_lo* );
    input clk;
    input data;
    output dgt_n;
    output dgt_p;
    input gt_ttl;
    input le;
    output lo;
    output \lo* ;
    input lo_sel;
    input \mtcd_lo* ;


    initial
        begin
        end

endmodule
