-- generated by newgenasym Thu Mar 05 15:15:58 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lo_gen is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DGT2:      OUT    STD_LOGIC;    
	DGT_N:     OUT    STD_LOGIC;    
	DGT_P:     OUT    STD_LOGIC;    
	GT_TTL:    IN     STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	LO_SEL:    IN     STD_LOGIC;    
	LO_STAR2:  OUT    STD_LOGIC;    
	LO_STAR_OUT_N: OUT    STD_LOGIC;    
	LO_STAR_OUT_P: OUT    STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC);
end lo_gen;
