-- generated by newgenasym Sat Feb 28 18:14:07 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lo_gen is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DGT_N:     OUT    STD_LOGIC;    
	DGT_P:     OUT    STD_LOGIC;    
	GT_TTL:    IN     STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	LO:        OUT    STD_LOGIC;    
	\lo*\:     OUT    STD_LOGIC;    
	LO_SEL:    IN     STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC);
end lo_gen;
