// generated by newgenasym  Sun Mar 01 23:38:24 2015


module fault_detection (bckp_clk, change_clk_n, change_clk_p, clk_reset_ecl,
        clk_reset_ttl, data_rdy, default_clk, max_count);
    input bckp_clk;
    output change_clk_n;
    output change_clk_p;
    input clk_reset_ecl;
    input clk_reset_ttl;
    input data_rdy;
    input default_clk;
    input [0:7] max_count;


    initial
        begin
        end

endmodule
