// generated by newgenasym  Tue Mar 03 15:29:31 2015


module fault_detection (bckp_clk, bckp_clk2_n, bckp_clk2_p, bckp_clk3_n,
        bckp_clk3_p, change_clk_n, change_clk_p, clk_reset_ecl,
        clk_reset_ttl, data_rdy, default_clk, default_clk2_n,
        default_clk2_p, max_count);
    input bckp_clk;
    output bckp_clk2_n;
    output bckp_clk2_p;
    output bckp_clk3_n;
    output bckp_clk3_p;
    output change_clk_n;
    output change_clk_p;
    input clk_reset_ecl;
    input clk_reset_ttl;
    input data_rdy;
    input default_clk;
    output default_clk2_n;
    output default_clk2_p;
    input [0:7] max_count;


    initial
        begin
        end

endmodule
