-- generated by newgenasym Tue Mar 03 15:29:31 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fault_detection is
    port (    
	BCKP_CLK:  IN     STD_LOGIC;    
	BCKP_CLK2_N: OUT    STD_LOGIC;    
	BCKP_CLK2_P: OUT    STD_LOGIC;    
	BCKP_CLK3_N: OUT    STD_LOGIC;    
	BCKP_CLK3_P: OUT    STD_LOGIC;    
	CHANGE_CLK_N: OUT    STD_LOGIC;    
	CHANGE_CLK_P: OUT    STD_LOGIC;    
	CLK_RESET_ECL: IN     STD_LOGIC;    
	CLK_RESET_TTL: IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	DEFAULT_CLK: IN     STD_LOGIC;    
	DEFAULT_CLK2_N: OUT    STD_LOGIC;    
	DEFAULT_CLK2_P: OUT    STD_LOGIC;    
	MAX_COUNT: IN     STD_LOGIC_VECTOR (0 TO 7));
end fault_detection;
