// generated by newgenasym  Wed Mar 04 12:20:04 2015


module ds90lv019 (de, din, dout, \dout* , gnd, re, ri, \ri* , rout, vcc);
    input de;
    input din;
    output dout;
    output \dout* ;
    input gnd;
    input re;
    input ri;
    input \ri* ;
    output rout;
    input vcc;


    initial
        begin
        end

endmodule
