// generated by newgenasym  Tue Jan 27 19:16:21 2015


module ds90lv019 (de, din, dout, \dout* , re, ri, \ri* , rout);
    input de;
    input din;
    output dout;
    output \dout* ;
    input re;
    input ri;
    input \ri* ;
    output rout;


    initial
        begin
        end

endmodule
