-- generated by newgenasym Wed Mar 04 12:20:04 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds90lv019 is
    port (    
	DE:        IN     STD_LOGIC;    
	DIN:       IN     STD_LOGIC;    
	DOUT:      OUT    STD_LOGIC;    
	\dout*\:   OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	RE:        IN     STD_LOGIC;    
	RI:        IN     STD_LOGIC;    
	\ri*\:     IN     STD_LOGIC;    
	ROUT:      OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end ds90lv019;
