// generated by newgenasym  Mon Sep 08 15:36:29 2014


module \10e131  (clk, d, en, q, \q* , r, s);
    parameter    size = 1;
    input clk;
    input [size-1:0] d;
    input en;
    output [size-1:0] q;
    output [size-1:0] \q* ;
    input r;
    input s;


    initial
        begin
        end

endmodule
