-- generated by newgenasym Wed Mar 04 17:06:07 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mpsh81 is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end mpsh81;
