-- generated by newgenasym Tue Jun 21 11:49:44 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MPSH81 is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end MPSH81;
