-- generated by newgenasym Wed Jun 11 17:05:15 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2t45 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end sn74lvc2t45;
