// generated by newgenasym  Fri Mar 06 18:35:31 2015


module general_utilities_ports (generic_delay_in, generic_delay_out, generic_pulse_out,
        pulse_inv_in, pulse_inv_out, ribbon_pulse_in_n,
        ribbon_pulse_in_p, ribbon_pulse_out_n,
        ribbon_pulse_out_p);
    output generic_delay_in;
    input generic_delay_out;
    input generic_pulse_out;
    output pulse_inv_in;
    input pulse_inv_out;
    output ribbon_pulse_in_n;
    output ribbon_pulse_in_p;
    input ribbon_pulse_out_n;
    input ribbon_pulse_out_p;


    initial
        begin
        end

endmodule
