// generated by newgenasym  Thu Apr 23 09:40:51 2015


module general_utilities_ports (generic_delay_in, pulse_inv_in, pulse_inv_out);
    output generic_delay_in;
    output pulse_inv_in;
    input pulse_inv_out;


    initial
        begin
        end

endmodule
