-- generated by newgenasym Fri Mar 06 18:35:31 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity general_utilities_ports is
    port (    
	GENERIC_DELAY_IN: OUT    STD_LOGIC;    
	GENERIC_DELAY_OUT: IN     STD_LOGIC;    
	GENERIC_PULSE_OUT: IN     STD_LOGIC;    
	PULSE_INV_IN: OUT    STD_LOGIC;    
	PULSE_INV_OUT: IN     STD_LOGIC;    
	RIBBON_PULSE_IN_N: OUT    STD_LOGIC;    
	RIBBON_PULSE_IN_P: OUT    STD_LOGIC;    
	RIBBON_PULSE_OUT_N: IN     STD_LOGIC;    
	RIBBON_PULSE_OUT_P: IN     STD_LOGIC);
end general_utilities_ports;
