-- generated by newgenasym Thu Apr 23 09:40:51 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity general_utilities_ports is
    port (    
	GENERIC_DELAY_IN: OUT    STD_LOGIC;    
	PULSE_INV_IN: OUT    STD_LOGIC;    
	PULSE_INV_OUT: IN     STD_LOGIC);
end general_utilities_ports;
