// generated by newgenasym  Wed Oct 29 14:53:51 2014


module ad8009 (\in+ , \in- , \output , \v+ , \v- );
    inout \in+ ;
    inout \in- ;
    inout \output ;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
