-- generated by newgenasym Wed Oct 29 14:53:51 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8009 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end ad8009;
