// generated by newgenasym  Fri May 27 11:15:36 2011


module el91l (in, \in* , out, \out* , vbb, vbb2);
    input in;
    input \in* ;
    output out;
    output \out* ;
    input vbb;
    input vbb2;


    initial
        begin
        end

endmodule
