-- generated by newgenasym Fri May 27 11:15:36 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity EL91L is
    port (    
	\in\:      IN     STD_LOGIC;    
	\in*\:     IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	\out*\:    OUT    STD_LOGIC;    
	VBB:       IN     STD_LOGIC;    
	VBB2:      IN     STD_LOGIC);
end EL91L;
