// generated by newgenasym  Mon May 25 11:13:04 2015


module lt1085ct (gnd, tab, vin, vout);
    inout gnd;
    inout tab;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
