-- generated by newgenasym Mon May 25 11:13:04 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt1085ct is
    port (    
	GND:       INOUT  STD_LOGIC;    
	TAB:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end lt1085ct;
