-- generated by newgenasym Thu Oct 16 19:05:30 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max9376 is
    port (    
	IN1:       INOUT  STD_LOGIC;    
	\in1*\:    IN     STD_LOGIC;    
	IN2:       IN     STD_LOGIC;    
	\in2*\:    IN     STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	\out1*\:   OUT    STD_LOGIC;    
	OUT2:      OUT    STD_LOGIC;    
	\out2*\:   OUT    STD_LOGIC);
end max9376;
