-- generated by newgenasym Wed Oct 29 16:43:32 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc10h104 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end mc10h104;
