-- generated by newgenasym Sat Feb 28 17:31:57 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc10h104 is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	B1:        IN     STD_LOGIC;    
	B2:        IN     STD_LOGIC;    
	B3:        IN     STD_LOGIC;    
	B4:        IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	\q4*\:     OUT    STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end mc10h104;
