-- generated by newgenasym Mon Aug 30 14:52:10 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10elt24\ is
    port (    
	D:         IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC);
end \10elt24\;
