// generated by newgenasym  Tue May 18 12:05:22 2010


module \10e101  (a, b, c, d, y, \y* );
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] b;
    input [size-1:0] c;
    input [size-1:0] d;
    output [size-1:0] y;
    output [size-1:0] \y* ;


    initial
        begin
        end

endmodule
