// generated by newgenasym  Wed Mar 04 19:06:12 2015


module ecl_translation (ecl_to_lvds_in, ecl_to_lvds_out_n, ecl_to_lvds_out_p,
        ecl_to_nim_in, ecl_to_nim_out, ecl_to_ttl_in,
        ecl_to_ttl_out, lvds_to_ecl_in_n, lvds_to_ecl_in_p,
        lvds_to_ecl_out_n, lvds_to_ecl_out_p, nim_to_ecl_in,
        nim_to_ecl_out, ttl_to_ecl_in, ttl_to_ecl_in_n,
        ttl_to_ecl_in_p);
    input ecl_to_lvds_in;
    input ecl_to_lvds_out_n;
    input ecl_to_lvds_out_p;
    input ecl_to_nim_in;
    input ecl_to_nim_out;
    input ecl_to_ttl_in;
    input ecl_to_ttl_out;
    input lvds_to_ecl_in_n;
    input lvds_to_ecl_in_p;
    input lvds_to_ecl_out_n;
    input lvds_to_ecl_out_p;
    input nim_to_ecl_in;
    input nim_to_ecl_out;
    input ttl_to_ecl_in;
    input ttl_to_ecl_in_n;
    input ttl_to_ecl_in_p;


    initial
        begin
        end

endmodule
