// generated by newgenasym  Fri Dec 17 19:09:48 2010


module xc2c64a (io1, io10, io11, io12, io13, io14, io15, io16, io17, io18,
        io19, io2, io20, io21, io22, io23, io24, io25, io26, io27, io28,
        io29, io3, io30, io31, io32, io33, io4, io5, io6, io7, io8, io9,
        tck, tdi, tdo, tms);
    inout io1;
    inout io10;
    inout io11;
    inout io12;
    inout io13;
    inout io14;
    inout io15;
    inout io16;
    inout io17;
    inout io18;
    inout io19;
    inout io2;
    inout io20;
    inout io21;
    inout io22;
    inout io23;
    inout io24;
    inout io25;
    inout io26;
    inout io27;
    inout io28;
    inout io29;
    inout io3;
    inout io30;
    inout io31;
    inout io32;
    inout io33;
    inout io4;
    inout io5;
    inout io6;
    inout io7;
    inout io8;
    inout io9;
    input tck;
    input tdi;
    output tdo;
    inout tms;


    initial
        begin
        end

endmodule
