// generated by genview  Thu Jan 15 20:26:26 1998

`timescale 1ns/100ps

module f06 (a, \y* );
    parameter    size = 1;
    input [size-1:0] a;
    output [size-1:0] \y* ;


    SIG74F06P  inst1[size-1:0] (/*.D0*/ a,
                               /*.Q0_*/ \y*  );
endmodule