// generated by newgenasym  Sun Mar 01 21:01:18 2015


module \74hct273  (cp, d0, d1, d2, d3, d4, d5, d6, d7, gnd, \mr* , q0, q1, q2, q3, q4, q5,
        q6, q7, vcc);
    input cp;
    input d0;
    input d1;
    input d2;
    input d3;
    input d4;
    input d5;
    input d6;
    input d7;
    input gnd;
    input \mr* ;
    output q0;
    output q1;
    output q2;
    output q3;
    output q4;
    output q5;
    output q6;
    output q7;
    input vcc;


    initial
        begin
        end

endmodule
