-- generated by newgenasym Sun Mar 01 21:01:18 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hct273\ is
    port (    
	CP:        IN     STD_LOGIC;    
	D0:        IN     STD_LOGIC;    
	D1:        IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	D5:        IN     STD_LOGIC;    
	D6:        IN     STD_LOGIC;    
	D7:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\mr*\:     IN     STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	Q5:        OUT    STD_LOGIC;    
	Q6:        OUT    STD_LOGIC;    
	Q7:        OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end \74hct273\;
