-- generated by newgenasym Tue Jan 27 16:28:25 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds90lv027 is
    port (    
	D:         IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC);
end ds90lv027;
