-- generated by newgenasym Tue Apr 05 20:01:44 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MMBTH81 is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end MMBTH81;
