// generated by newgenasym  Wed Oct 08 10:54:00 2014


module ths3062 (\in+ , \in- , out, \vcc+ , \vcc- );
    inout \in+ ;
    inout \in- ;
    inout out;
    input \vcc+ ;
    input \vcc- ;


    initial
        begin
        end

endmodule
