-- generated by newgenasym Wed Oct 08 10:54:00 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ths3062 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\vcc+\:    IN     STD_LOGIC;    
	\vcc-\:    IN     STD_LOGIC);
end ths3062;
