-- generated by newgenasym Tue May 18 12:04:11 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TESTPOINT_L is
    port (    
	A:         INOUT  STD_LOGIC);
end TESTPOINT_L;
