// generated by newgenasym  Sun Mar 01 00:37:03 2015


module mc10h125 (d1, \d1* , d2, \d2* , d3, \d3* , d4, \d4* , gnd, q1, q2, q3, q4, vbb, vcc,
        vee);
    input d1;
    input \d1* ;
    input d2;
    input \d2* ;
    input d3;
    input \d3* ;
    input d4;
    input \d4* ;
    input gnd;
    output q1;
    output q2;
    output q3;
    output q4;
    output vbb;
    input vcc;
    input vee;


    initial
        begin
        end

endmodule
