-- generated by newgenasym Sun Mar 01 00:37:03 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc10h125 is
    port (    
	D1:        IN     STD_LOGIC;    
	\d1*\:     IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	\d2*\:     IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	\d3*\:     IN     STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	\d4*\:     IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	VBB:       OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end mc10h125;
