// generated by newgenasym  Tue Aug 19 14:22:07 2014


module lm7171 (\in+ , \in- , \output , \v+ , \v- );
    inout \in+ ;
    inout \in- ;
    inout \output ;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
