-- generated by newgenasym Tue Aug 19 14:22:07 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm7171 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end lm7171;
