// generated by newgenasym  Fri Nov 14 13:46:41 2014


module \10h116  (a, \b* , v, y, \y* );
    parameter    section = 1;
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] \b* ;
    input v;
    output [size-1:0] y;
    output [size-1:0] \y* ;


    initial
        begin
        end

endmodule
