-- generated by newgenasym Fri Nov 14 13:46:41 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h116\ is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\b*\:      IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	V:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y*\:      OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \10h116\;
