// generated by newgenasym  Tue May 18 12:03:46 2010


module res_l (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
