-- generated by newgenasym Mon Sep 15 09:27:37 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity f273 is
    port (    
	CL:        IN     STD_LOGIC;    
	CP:        IN     STD_LOGIC;    
	D:         IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC);
end f273;
