-- generated by newgenasym Thu Jan 29 10:48:59 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sip_header_2pin is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end sip_header_2pin;
