-- generated by newgenasym Wed Jan 12 10:18:41 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xc2c256 is
    port (    
	IO1:       INOUT  STD_LOGIC;    
	IO10:      INOUT  STD_LOGIC;    
	IO11:      INOUT  STD_LOGIC;    
	IO12:      INOUT  STD_LOGIC;    
	IO13:      INOUT  STD_LOGIC;    
	IO14:      INOUT  STD_LOGIC;    
	IO15:      INOUT  STD_LOGIC;    
	IO16:      INOUT  STD_LOGIC;    
	IO17:      INOUT  STD_LOGIC;    
	IO18:      INOUT  STD_LOGIC;    
	IO19:      INOUT  STD_LOGIC;    
	IO2:       INOUT  STD_LOGIC;    
	IO20:      INOUT  STD_LOGIC;    
	IO21:      INOUT  STD_LOGIC;    
	IO22:      INOUT  STD_LOGIC;    
	IO23:      INOUT  STD_LOGIC;    
	IO24:      INOUT  STD_LOGIC;    
	IO25:      INOUT  STD_LOGIC;    
	IO26:      INOUT  STD_LOGIC;    
	IO27:      INOUT  STD_LOGIC;    
	IO28:      INOUT  STD_LOGIC;    
	IO29:      INOUT  STD_LOGIC;    
	IO3:       INOUT  STD_LOGIC;    
	IO30:      INOUT  STD_LOGIC;    
	IO31:      INOUT  STD_LOGIC;    
	IO32:      INOUT  STD_LOGIC;    
	IO33:      INOUT  STD_LOGIC;    
	IO4:       INOUT  STD_LOGIC;    
	IO5:       INOUT  STD_LOGIC;    
	IO6:       INOUT  STD_LOGIC;    
	IO7:       INOUT  STD_LOGIC;    
	IO8:       INOUT  STD_LOGIC;    
	IO9:       INOUT  STD_LOGIC;    
	TCK:       IN     STD_LOGIC;    
	TDI:       IN     STD_LOGIC;    
	TDO:       OUT    STD_LOGIC;    
	TMS:       INOUT  STD_LOGIC);
end xc2c256;
